### ISSUE TITLE
访问控制列表的样式有问题，烦请修复一下，谢谢！

### ISSUE THREAD

**Issue by viagram** [Openwrt-Passwall/openwrt-passwall#1279]
![ps](https://user-images.githubusercontent.com/18513535/123383529-e27c4280-d5c5-11eb-8a0d-c04dea358b2d.png)

**Comment by handsomeji** [comment]
主题问题

**Comment by viagram** [comment]
> 主题问题

我编译的是默认：Bootstrap
请问哪个主题适配好些？

**Comment by handsomeji** [comment]
你可以看看其它主题会不会
我用Lienol的luci17.01是正常显示的

**Comment by viagram** [comment]
> 你可以看看其它主题会不会
> 我用Lienol的luci17.01是正常显示的

谢谢

**Comment by jh0072110** [comment]
> 你可以看看其它主题会不会
> 我用Lienol的luci17.01是正常显示的

说到主题问题，借楼说一下就不开新讨论了咳咳：
![image](https://user-images.githubusercontent.com/50496854/123403007-ea92ad00-d5da-11eb-9859-58a2174b0992.png)
From: https://github.com/jerrykuku/luci-theme-argon/issues/199
