### ISSUE TITLE
关于防火墙redirect和tproxy请教

### ISSUE THREAD

**Issue by WROIATE** [Openwrt-Passwall/openwrt-passwall#1288]
我阅读了xray的[透明代理教程](https://xtls.github.io/documents/level-2/transparent_proxy/transparent_proxy/)，发现全篇使用的是mangle表，没有使用nat表。
然后我去看了下passwall的防火规则，发现v4同时存在mangle的tproxy和nat的redirect规则，请问这里nat的redirect规则起到什么作用？我观察流量统计，流量也几乎全走的mangle表，差不多6g，而nat只有1.6m。

**Comment by handsomeji** [comment]
目前TCP只有brook使用mangle，其他类型使用nat redirect。
UDP只能使用mangle tproxy.
