### ISSUE TITLE
最新Naiveproxy编译不通过

### ISSUE THREAD

**Issue by ddnsoft** [Openwrt-Passwall/openwrt-passwall#1289]
如题，昨晚更新的Naiveproxy编译不通过

**Comment by handsomeji** [comment]
Please revert by yourself or use the official openwrt master branch.

**Comment by microdockman** [comment]
> 如题，昨晚更新的Naiveproxy编译不通过



staging_dir\hostpkg\bin  目录下加个nijia文件https://github.com/ninja-build/ninja/releases/tag/v1.10.2

**Comment by ddnsoft** [comment]
我看了下 那个文件是有的 还是编译不通过 ![image](https://user-images.githubusercontent.com/75249507/124338374-38f70b80-dbda-11eb-876b-eef8d7b3cfad.jpeg)

**Comment by handsomeji** [comment]
用的固件源码是什么 哪个分支？

**Comment by microdockman** [comment]
> > 如题，昨晚更新的Naiveproxy编译不通过
> 
> staging_dir\hostpkg\bin 目录下加个nijia文件https://github.com/ninja-build/ninja/releases/tag/v1.10.2

还需要加下权限（用户组1000，1000），chmod 777 staging_dir/hostpkg/bin/ninja  
固件源 https://github.com/openwrt/openwrt

**Comment by lllrrr2** [comment]
> > 如题，昨晚更新的Naiveproxy编译不通过
> 
> staging_dir\hostpkg\bin 目录下加个nijia文件https://github.com/ninja-build/ninja/releases/tag/v1.10.2

加了也编译不成功，用的是官源的19.07分支。将改回 $(STAGING_DIR_HOSTPKG)/bin/ninja -C "out/Release" naive ; \ 就可以
