### ISSUE TITLE
关于直连名单无法生效问题

### ISSUE THREAD

**Issue by hecarli555** [Openwrt-Passwall/openwrt-passwall#1290]
我是爱快虚拟的openwrt，然后用的passwall，手动添加了一下国内pt站点域名进直连名单中，保存并应用后经测试无法生效，登录各pt站的网页的时候发现还是走的代理。。。请问这是什么情况呢？

**Comment by handsomeji** [comment]
清空IPSET 清空dns缓存

**Comment by hecarli555** [comment]
dns是怎么清空…求教😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xiaorouji ***@***.***&gt;
发送时间: 2021年7月12日 22:36
收件人: xiaorouji/openwrt-passwall ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[xiaorouji/openwrt-passwall] 关于直连名单无法生效问题 (#1290)





 
清空IPSET 清空dns缓存
