### ISSUE TITLE
使用访问控制之后出现DNS解析问题

### ISSUE THREAD

**Issue by bigpao88** [Openwrt-Passwall/openwrt-passwall#1292]
您好，最近使用中发现一个问题。当在访问控制中添加了项目并启用，无论设置为何种代理模式，只要打开一个有错误的网址，就会显示无法找到XXX.XXX.XXX的DNS地址，正在诊断该问题。随后所有网页均无法打开，只有重启PASSWALL主开关才可以恢复。如果不启用访问控制，打开错误网址只会显示检查XXX.XXX.XXX中是否有拼写错误，但是并不影响后续其他网页的打开。想请教大佬，有没有什么方法可以解决吗?

**Comment by izerosoul** [comment]
有错误的网址是什么意思？你是指的DNS不正确（无法解析）的网址吗？

我之前也遇到DNS无法解析的问题(https://github.com/xiaorouji/openwrt-passwall/discussions/1222),  一直没查出具体原因，Bug触发也不稳定，不容易稳定重现

**Comment by bigpao88** [comment]
可以稳定重现，只要添加了访问控制，尝试打开一个不存在的网页，例如我托管了一个域名abc.ml，可以正常打开，但是某一次手误输入了abcd.ml，就会出现该bug，尝试打开abcd.ml失败之后，打开任何网页都会显示dns解析失败，只有重新开关passwall才可以正常打开网页。

**Comment by handsomeji** [comment]
无法复现，试试4-28，不保留配置重新配置一遍

**Comment by BGzErol** [comment]
![WDQIU %NPK4 ~T$0IBA(XBJ](https://user-images.githubusercontent.com/61510455/125823235-8f349de9-1dcb-46c2-a904-7ba5e51e5810.png)
没问题啊，在abcd.ml打开失败后我还是能加载我浏览器收藏栏上的所有网页
4-27的

**Comment by bigpao88** [comment]
好的，谢谢各位大佬，我怀疑可能是固件的原因，换个固件好像就可以了。不好意思打扰了。

**Comment by YugaoX** [comment]
我也有这样的问题 一设置控制访问就出现了无法解析dns的问题，现在初步的解决方案是把53端口禁止走upd代理
