### ISSUE TITLE
最新版本haproxy运行一段时间会高CPU占用

### ISSUE THREAD

**Issue by db-one** [Openwrt-Passwall/openwrt-passwall#1293]
![image](https://user-images.githubusercontent.com/20243226/124460234-b16bf100-ddc1-11eb-8651-4fef4e89123e.png)
最新版本haproxy运行一段时间会高CPU占用，最高占用到200%，最终甚至偶尔导致openwrt重启，之前的版本没发现这个问题，重启后暂时正常，运行一段时间后又重新出现

版本是2.4.1
![image](https://user-images.githubusercontent.com/20243226/124460304-c9437500-ddc1-11eb-9565-b7d78a03ee3a.png)

**Comment by db-one** [comment]
系统日志和内核日志里面没有任何信息

**Comment by hcym** [comment]
x86遇到过两次，arm的一直正常

**Comment by db-one** [comment]
> x86遇到过两次，arm的一直正常

嗯  我的就是X86的

**Comment by db-one** [comment]
我之前的解决方法是，拉取大雕的旧版本haproxy，但是最近大雕的也升级到2.4.1版本了，就也这样了，好像是2.4.0之后版本都有这个问题，之前的版本是正常的

**Comment by chenxuan5858** [comment]
我也遇到了问题，暂时无解

**Comment by db-one** [comment]
我从历史版本里面找到了2.2.14版本的，先继续退回旧版本了，新版本的不知道是自身问题还是和配置文件的兼容问题，暂时先不管他了，等大佬们修复吧，先暂时用旧版的

**Comment by chenxuan5858** [comment]
> 我从历史版本里面找到了2.2.14版本的，先继续退回旧版本了，新版本的不知道是自身问题还是和配置文件的兼容问题，暂时先不管他了，等大佬们修复吧，先暂时用旧版的

是源码回退编译的吗，可否吧源码地址分享一下？

**Comment by db-one** [comment]
> > 我从历史版本里面找到了2.2.14版本的，先继续退回旧版本了，新版本的不知道是自身问题还是和配置文件的兼容问题，暂时先不管他了，等大佬们修复吧，先暂时用旧版的
> 
> 是源码回退编译的吗，可否吧源码地址分享一下？

https://github.com/db-one/openwrt-packages

**Comment by hcym** [comment]
嫁接疗法非常完美，cpu再也见不到发飙了😂
感谢分享

**Comment by handsomeji** [comment]
2.4.0后据说是大更新，我抽空研究一下

**Comment by romanticfaery** [comment]
同问，我也发现这个问题， 经反复测试，当负载均衡出现  health： failed check 状态， 就开始飙升  。 所以只要看到界面  有 err状态， 一定开始飙升了

**Comment by romanticfaery** [comment]
猜测  与 节点质量的判断 有关系

**Comment by db-one** [comment]
这个状态在哪里看的？

**Comment by db-one** [comment]
大佬已经出现了，估计问题得到解决也不远了

**Comment by romanticfaery** [comment]
界面有一列 叫chk   只有有数据  必发飙
# @ #

**Comment by db-one** [comment]
> 界面有一列 叫chk 只有有数据 必发飙
> 
> # @

好的   谢谢  看到了

**Comment by handsomeji** [comment]
可以尝试使用最新haproxy 2.4.2 试试，貌似修复了挺多问题？
http://www.haproxy.org/download/2.4/src/CHANGELOG

**Comment by db-one** [comment]
有人去大雕那里提交一下新版吗   不太会提交Pull

**Comment by romanticfaery** [comment]
tag.gz怎么安装到op中 不会使用

**Comment by romanticfaery** [comment]
谁给我说下 我帮你们试试最新haproxy

**Comment by db-one** [comment]
> 谁给我说下 我帮你们试试最新haproxy

packages/net/haproxy/get-latest-patches.sh里面
BASE_TAG=v2.4.1改成BASE_TAG=v2.4.2
packages/net/haproxy/Makefile里面
PKG_VERSION:=2.4.1改成PKG_VERSION:=2.4.2
PKG_HASH:=1b2458b05e923d70cdc00a2c8e5579c2fcde9df16bbed8955f3f3030df14e62e
改成
PKG_HASH:=edf9788f7f3411498e3d7b21777036b4dc14183e95c8e2ce7577baa0ea4ea2aa
应该是只有这三个地方

**Comment by chenxuan5858** [comment]
> > > 我从历史版本里面找到了2.2.14版本的，先继续退回旧版本了，新版本的不知道是自身问题还是和配置文件的兼容问题，暂时先不管他了，等大佬们修复吧，先暂时用旧版的
> > 
> > 
> > 是源码回退编译的吗，可否吧源码地址分享一下？
> 
> https://github.com/db-one/openwrt-packages

感谢！！

**Comment by chenxuan5858** [comment]
> > > 我从历史版本里面找到了2.2.14版本的，先继续退回旧版本了，新版本的不知道是自身问题还是和配置文件的兼容问题，暂时先不管他了，等大佬们修复吧，先暂时用旧版的
> > 
> > 
> > 是源码回退编译的吗，可否吧源码地址分享一下？
> 
> https://github.com/db-one/openwrt-packages

全身舒爽，感谢感谢

**Comment by bilibilistack** [comment]
确实有这样的问题，我是ARM版本的也有

**Comment by ali2liu** [comment]
> > 谁给我说下 我帮你们试试最新haproxy
> 
> packages/net/haproxy/get-latest-patches.sh里面
> BASE_TAG=v2.4.1改成BASE_TAG=v2.4.2
> packages/net/haproxy/Makefile里面
> PKG_VERSION:=2.4.1改成PKG_VERSION:=2.4.2
> PKG_HASH:=1b2458b05e923d70cdc00a2c8e5579c2fcde9df16bbed8955f3f3030df14e62e
> 改成
> PKG_HASH:=edf9788f7f3411498e3d7b21777036b4dc14183e95c8e2ce7577baa0ea4ea2aa
> 应该是只有这三个地方

依次方法编译的5.10.46内核中2.4.2-1haproxy已经运行17个小时，没有发飙！

**Comment by hcym** [comment]
不追星了，就是负载均衡，还是老版本

**Comment by db-one** [comment]
大雕那里已经更新到2.4.2了，有人编译过怎么样吗？

**Comment by hcym** [comment]
大雕能启动，但是ipv6节点不行，pass新版可以用6的，但是节点不能手动加，只能用已有列表里的😂

**Comment by db-one** [comment]
ipv4正常吧？ 还有没有高负载的问题了

**Comment by db-one** [comment]
最新版本用了几天，暂时没有复现上面的问题，关闭了，谢谢各位大佬，辛苦了
