### ISSUE TITLE
trojan-go的指纹伪造无法使用

### ISSUE THREAD

**Issue by CC-3301** [Openwrt-Passwall/openwrt-passwall#1299]
trojan-go将指纹伪造设置成firefox或chrome都会自动变回停用，是bug吗？
xray的指纹伪造设置就正常

今天刚编译的passwall最新版本

**Comment by handsomeji** [comment]
BUG，下个版本修复

**Comment by CC-3301** [comment]
收到，幸苦大佬

**Comment by xiaorouji** [comment]
先开着吧，我怕我会忘记

**Comment by ShoukakuChuuCC** [comment]
大佬顺便问一下 我平时常用chrome浏览器，指纹伪造用chrome还是firefox？随便选吗还是说最好和真实浏览器一样

**Comment by handsomeji** [comment]
Fix.

**Comment by xllxll** [comment]
大大，你好，这个BUG又出现了？有什么应急办法吗？

**Comment by xllxll** [comment]
> Fix.

大大，你好，这个BUG又出现了？有什么应急办法吗？
