### ISSUE TITLE
4-27 使用自动切换功能主节点会断流，频繁的切换

### ISSUE THREAD

**Issue by yunxi993** [Openwrt-Passwall/openwrt-passwall#1301]
原本以为是节点问题，换成一个很稳的节点仍然频繁断流、切换，关闭自动切换后断流就没有出现。
主节点vless，自动切换备用节点 Vmess

**Comment by izerosoul** [comment]
#1221 解决了这个问题，是curl的问题

**Comment by yunxi993** [comment]
> #1221 解决了这个问题，是curl的问题

嗯，这个当时又关注，但是现在这个问题又复现了.我是4-27最新的版本.

**Comment by izerosoul** [comment]
> > #1221 解决了这个问题，是curl的问题
> 
> 嗯，这个当时又关注，但是现在这个问题又复现了.我是4-27最新的版本.

最新版不是都7-11了么？

你可以确认下 /root/usr/share/passwall/test.sh 文件中有没有--retry-all-errors参数

**Comment by yunxi993** [comment]
> > > #1221 解决了这个问题，是curl的问题
> > 
> > 
> > 嗯，这个当时又关注，但是现在这个问题又复现了.我是4-27最新的版本.
> 
> 最新版不是都7-11了么？
> 
> 你可以确认下 /root/usr/share/passwall/test.sh 文件中有没有--retry-all-errors参数

passwall最新的不是才4-28吗？
有

**Comment by izerosoul** [comment]
> > > > #1221 解决了这个问题，是curl的问题
> > > 
> > > 
> > > 嗯，这个当时又关注，但是现在这个问题又复现了.我是4-27最新的版本.
> > 
> > 
> > 最新版不是都7-11了么？
> > 你可以确认下 /root/usr/share/passwall/test.sh 文件中有没有--retry-all-errors参数
> 
> passwall最新的不是才4-28吗？
> 有

你的问题可能跟 #1224 提到的相同，你检查下你的curl是不是不支持--retry-all-errors这个参数，需要升级curl，或者直接整个升级到最新版，你在哪下的包怎么会最新才4-28

**Comment by yunxi993** [comment]
> > > > > #1221 解决了这个问题，是curl的问题
> > > > 
> > > > 
> > > > 嗯，这个当时又关注，但是现在这个问题又复现了.我是4-27最新的版本.
> > > 
> > > 
> > > 最新版不是都7-11了么？
> > > 你可以确认下 /root/usr/share/passwall/test.sh 文件中有没有--retry-all-errors参数
> > 
> > 
> > passwall最新的不是才4-28吗？
> > 有
> 
> 你的问题可能跟 #1224 提到的相同，你检查下你的curl是不是不支持--retry-all-errors这个参数，需要升级curl，或者直接整个升级到最新版，你在哪下的包怎么会最新才4-28

我的情况还是有一点区别得，我开启自动切换并不是无线切换，而是节点用一会儿就断流导致自动切换。
TG群这两天已经有好几个群有人反馈这么问题了。
自己编译得4-28啊.
