### ISSUE TITLE
Hi, is it possible to make all my traffic passthrough, except only those Netflix related.

### ISSUE THREAD

**Issue by kodbuzz** [Openwrt-Passwall/openwrt-passwall#1302]
There are 5 modes down there in the drop list, 

no proxy,
global, 
gfw, 
china, 
not china

Unfortunately none of them seems to fit, is there a way to make my own one which effects only to Netflix? 

Thanks.

**Comment by hplee0120** [comment]
![8B85D8A1-1C3C-405A-A98E-2C3A9F5E670F](https://user-images.githubusercontent.com/55278556/125204170-792b4d80-e2ae-11eb-9990-af4d71ee2636.jpeg)
![EFAEC0C7-6B0B-45F0-9577-445C65333F9F](https://user-images.githubusercontent.com/55278556/125204174-7cbed480-e2ae-11eb-9bb2-22f725753e4e.jpeg)

**Comment by kodbuzz** [comment]
Thanks, I tried to find out exactly the same page but unfortunately I couldn't, probably version not match? I'm on 4-27 that I think it's up to date. Could you point out how you get there? Thank you.

**Comment by hplee0120** [comment]
> Thanks, I tried to find out exactly the same page but unfortunately I couldn't, probably version not match? I'm on 4-27 that I think it's up to date. Could you point out how you get there? Thank you.

Yes, I am also 4.27

Rule Manage menu page Pull down to create your own shunt. Then select TCP Node:Xray-shunt on the home page
Choose the right server for your own shunt

**Comment by hplee0120** [comment]
> Thanks, I tried to find out exactly the same page but unfortunately I couldn't, probably version not match? I'm on 4-27 that I think it's up to date. Could you point out how you get there? Thank you.

The plug-in itself has a streaming of Netflix, so you only need to select Xray-shunt for the main interface of TCP Node. Choose the server you need for Netflix shunt. Other services can default to direct connections without affecting other services.

**Comment by kodbuzz** [comment]
> > Thanks, I tried to find out exactly the same page but unfortunately I couldn't, probably version not match? I'm on 4-27 that I think it's up to date. Could you point out how you get there? Thank you.
> 
> Yes, I am also 4.27
> 
> Rule Manage menu page Pull down to create your own shunt. Then select TCP Node:Xray-shunt on the home page
> Choose the right server for your own shunt

Thank you, I've created a Xray Shunt Rule under 'Rule Manage', double checked that it has been saved and everything is just fine, then the weird part is, there's nothing but my server nodes from the drop list under 'Basic Setting' (aka home page), I tried to refresh and even got the router reboot twice, but still no luck.

I'm pretty confused.

**Comment by hplee0120** [comment]
> > > Thanks, I tried to find out exactly the same page but unfortunately I couldn't, probably version not match? I'm on 4-27 that I think it's up to date. Could you point out how you get there? Thank you.
> > 
> > 
> > Yes, I am also 4.27
> > Rule Manage menu page Pull down to create your own shunt. Then select TCP Node:Xray-shunt on the home page
> > Choose the right server for your own shunt
> 
> Thank you, I've created a Xray Shunt Rule under 'Rule Manage', double checked that it has been saved and everything is just fine, then the weird part is, there's nothing but my server nodes from the drop list under 'Basic Setting' (aka home page), I tried to refresh and even got the router reboot twice, but still no luck.
> 
> I'm pretty confused.

You need the TCP node to choose for this. The diversion of other services, including your own, will occur

![8D90F337-56F8-49B6-B89B-409A5D337BDB](https://user-images.githubusercontent.com/55278556/125205447-e2ae5a80-e2b4-11eb-9eb2-33d840fb91c1.jpeg)

**Comment by kodbuzz** [comment]
![Screenshot 2021-07-11 210208](https://user-images.githubusercontent.com/77547202/125205545-766b3100-e28b-11eb-8fc5-c9868eec82f4.png)

well yeah, but there's no such an item, any idea?

**Comment by hplee0120** [comment]
> ![Screenshot 2021-07-11 210208](https://user-images.githubusercontent.com/77547202/125205545-766b3100-e28b-11eb-8fc5-c9868eec82f4.png)
> 
> well yeah, but there's no such an item, any idea?

In the plug-in I compiled, this option is available by default, and it's not clear why you disappeared. The problem is also well solved, just add one server manually. The type and protocol are selected as such.

![1B3B701D-831B-42E5-9658-3060F62226E4](https://user-images.githubusercontent.com/55278556/125205768-77658800-e2b6-11eb-9ab4-a97e3bb3b8d8.jpeg)

**Comment by kodbuzz** [comment]
@hplee0120 

Sadly, TCP indicate leaves NOT RUNNING on shunt node, and the more weird thing is my server node won't stop after 'main switch' got unchecked. I think maybe I messed up during compiling or something.

Anyway, thank you so much for your time.

btw do you happen to have binary for ARM7 that I can download somewhere? Again, Thank you.

**Comment by hplee0120** [comment]
> @hplee0120
> 
> Sadly, TCP indicate leaves NOT RUNNING on shunt node, and the more weird thing is my server node won't stop after 'main switch' got unchecked. I think maybe I messed up during compiling or something.
> 
> Anyway, thank you so much for your time.
> 
> btw do you happen to have binary for ARM7 that I can download somewhere? Again, Thank you.

I suspect it may be that you are compiling without the necessary dependencies, or that the compiled OpenWrt source code is not compatible with the plug-in. All of the above is possible. Because it works in my use.
Sorry, I'm not using this architecture

**Comment by kodbuzz** [comment]
UPDATE:

Since the proxy won't stop from LuCI, I went to CLI and finally have it stopped by command 'service passwall stop', then I set the node back to shunt then I put 'service passwall start' in CLI, guess what, although an error jumped up but it worked. 

I got this error:
> RTNETLINK answers: Permission denied

and it won't survive reboot, I'll try to figure out the cause later and report back.

**Comment by kodbuzz** [comment]
> > @hplee0120
> > Sadly, TCP indicate leaves NOT RUNNING on shunt node, and the more weird thing is my server node won't stop after 'main switch' got unchecked. I think maybe I messed up during compiling or something.
> > Anyway, thank you so much for your time.
> > btw do you happen to have binary for ARM7 that I can download somewhere? Again, Thank you.
> 
> I suspect it may be that you are compiling without the necessary dependencies, or that the compiled OpenWrt source code is not compatible with the plug-in. All of the above is possible. Because it works in my use.
> Sorry, I'm not using this architecture

No problem, you helped alot already.

Since it is my own problem and pretty much an single case, I'm gonna close the issue.
