### ISSUE TITLE
无法使用Xray的gRPC传输协议

### ISSUE THREAD

**Issue by CC-3301** [Openwrt-Passwall/openwrt-passwall#1303]
Xray，Vless+gRPC+TLS，谷歌连接测试失败
![image](https://user-images.githubusercontent.com/38343280/125195863-3eafb980-e28a-11eb-86cb-1e54354f16eb.png)
使用ShadowsocksR Plus+测试则能正常使用

**Comment by LOVECHEN** [comment]
xtls 好像也不能用

**Comment by CC-3301** [comment]
> xtls 好像也不能用

xtls能用的 请检查配置

**Comment by naturecurly** [comment]
因为passwall没办法设置alpn，估计服务端nginx回落只过滤了alpn为h2的数据。

**Comment by CC-3301** [comment]
谢谢，学习了，我一直都是使用官方推荐的第三方脚本搭建
https://github.com/kirin10000/Xray-script
看了下xray的配置文件，确实是过滤了，刚刚手动搭建不配置fallback，现在能用gRPC了

**Comment by CC-3301** [comment]
希望passwall能推出设置alpn的选项
