### ISSUE TITLE
passwall 服务端 127.0.0.1:53: server misbehaving

### ISSUE THREAD

**Issue by sheiy** [Openwrt-Passwall/openwrt-passwall#1305]
![image](https://user-images.githubusercontent.com/12210038/125280829-19818080-e348-11eb-8287-f49913400f3e.png)
![image](https://user-images.githubusercontent.com/12210038/125280892-2900c980-e348-11eb-895f-b3e7436e255c.png)

[ERROR] 2021/07/12 11:32:44 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial www.gstatic.com:80 | dial tcp: lookup www.gstatic.com on 127.0.0.1:53: server misbehaving

**Comment by handsomeji** [comment]
试试换成trojan-plus或xray trojan
