### ISSUE TITLE
请教一下如何编译可以让v2ray和xray共存…（或者如何编译使用v2ray）

### ISSUE THREAD

**Issue by jh0072110** [Openwrt-Passwall/openwrt-passwall#1308]
额…其实就是xray现在在连grpc的时候有点小问题（会睡死）…v2ray好像解决了这个问题…其实xray的pr也解决了这个问题但是r大最近挺忙一直没有merge……
所以想用grpc的话大约也许可能得用一下v2ray…
编译的时候已经莫得这个选项了……
该怎么编译才能玩啊……

**Comment by a13547** [comment]
服务端换成v2ray就行了。
xray解决grpc的那个PR似乎是要在服务端和客户端同时设置健康检查选项。之前只在服务端设置过无效。我把那几个健康检查选项写死在gen_xray.json里面，然而并没有什么用。

**Comment by jh0072110** [comment]
> 服务端换成v2ray就行了。
> xray解决grpc的那个PR似乎是要在服务端和客户端同时设置健康检查选项。之前只在服务端设置过无效。我把那几个健康检查选项写死在gen_xray.json里面，然而并没有什么用。

只改服务端会不会有点草率啊😅

**Comment by a13547** [comment]
我又试了下，xray那个PR可以解决问题，不过就是客户端和服务端都要设置，写死在gen_xray.json里面就能生成新的配置文件。

**Comment by jh0072110** [comment]
> 我又试了下，xray那个PR可以解决问题，不过就是客户端和服务端都要设置，写死在gen_xray.json里面就能生成新的配置文件。

对 那个pr解决问题但是…奈何r大没空合并…我手动切成v2 4.41了试一晚上看管不管用

**Comment by jh0072110** [comment]
试了一晚上 看起来v2ray也并没有解决清楚这个问题 唉关了
