### ISSUE TITLE
luci-app-passwall 4-28 在官方openwrt-19.07源码编译后打不开管理页面

### ISSUE THREAD

**Issue by ydch** [Openwrt-Passwall/openwrt-passwall#1310]
显示

/usr/lib/lua/luci/controller/passwall.lua:11: module 'luci.model.cbi.passwall.api.kcptun' not found:
	no field package.preload['luci.model.cbi.passwall.api.kcptun']
	no file './luci/model/cbi/passwall/api/kcptun.lua'
	no file '/usr/share/lua/luci/model/cbi/passwall/api/kcptun.lua'
	no file '/usr/share/lua/luci/model/cbi/passwall/api/kcptun/init.lua'
	no file '/usr/lib/lua/luci/model/cbi/passwall/api/kcptun.lua'
	no file '/usr/lib/lua/luci/model/cbi/passwall/api/kcptun/init.lua'
	no file './luci/model/cbi/passwall/api/kcptun.so'
	no file '/usr/lib/lua/luci/model/cbi/passwall/api/kcptun.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/passwall.lua:11: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1081: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1192: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:694: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:795: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

**Comment by liverpool-fc** [comment]
opkg install luci-compat
