### ISSUE TITLE
官方openwrt 21.02.0-rc3中安装后在登录路由器前会暴露菜单

### ISSUE THREAD

**Issue by liverpool-fc** [Openwrt-Passwall/openwrt-passwall#1311]
![photo_2021-07-15_22-50-23](https://user-images.githubusercontent.com/87487305/125808669-6551f8a6-54c0-49bd-bd34-28d1c86feb48.jpg)
如图所示，使用官方openwrt 21.02.0-rc3 sdk编译

**Comment by handsomeji** [comment]
旧版会吗

**Comment by liverpool-fc** [comment]
我的设备是树莓派4，21.02开始才有稳定版适配，三个rc版本都这样

**Comment by liverpool-fc** [comment]
> 旧版会吗

我的设备是树莓派4，21.02开始才有稳定版适配，三个rc版本都这样

**Comment by handsomeji** [comment]
试试最新源码

**Comment by liverpool-fc** [comment]
> 试试最新源码

已修复，感谢~！
