### ISSUE TITLE
Lean源码下编译固件 passwall无法运行

### ISSUE THREAD

**Issue by ghost** [Openwrt-Passwall/openwrt-passwall#1312]
一个多月之前开始一直这样，编译后passwall都无法运行 所有插件保持默认 就添加passwall也无法运行 排除了与其他插件冲突的假设
编译环境是ESXI虚拟 ubuntu18 20 21 桌面版本 服务器版本（未尝试github云编译）都试过 都在非root账户下编译  问题一直存在
解决方法是赋予  /etc/init/d下passwall passwall_server 及/usr/share/passwall/下所有文件755权限（这些权限默认是644 
 ）
这样操作后才能运行  否则会一直显示 tcp未运行  DSN未运行等等
希望作者解决此问题

**Comment by handsomeji** [comment]
脚本本身就是755权限，请使用git clone 而非自己下载解压然后拖进源码里面。这样权限是会变成0644的

**Comment by ghost** [comment]
> 脚本本身就是755权限，请使用git clone 而非自己下载解压然后拖进源码里面。这样权限是会变成0644的

谢谢大佬 我还真是下载后拖到源码里面的  下次编译直接用git命令试试
