### ISSUE TITLE
brook长时占用100%CPU / ss-redir长时占用25%

### ISSUE THREAD

**Issue by ChienHoWee** [Openwrt-Passwall/openwrt-passwall#1313]
树莓派4B，passwall版本4_28，使用brook时会跑满CPU，切换1-2次节点以后必定出现这个情况，之前版本已经有这个情况出现。killall brook进程以后再运行就会正常，之后再切换节点也不会出现这个问题。（更新：切换到SSRP后再切回passwall的Brook，这个问题又会重现。）
另外，SS/SSR也会这样，只是会跑满单核，25%占用，且killall ss-redir / ssr-redir再运行还会继续占用。将节点类型转至xray兼容的SS以后没有这个问题。
Lean的源码，ssrp下使用SS没有这个问题。

![Screenshot 2021-07-16 103258](https://user-images.githubusercontent.com/51148262/125884469-9c88bf29-7838-4ee0-b62a-dcbf3f736031.png)

**Comment by handsomeji** [comment]
没有复现
