### ISSUE TITLE
passwall & vssr  泄漏本地 ISP

### ISSUE THREAD

**Issue by la8896** [Openwrt-Passwall/openwrt-passwall#1314]
在全局模式下,会泄漏本地 ISP
测试网站
https://www.myip.com/

但使用v2rayN & v2rayng & qv2ray是不会泄漏本地 ISP
![110757](https://user-images.githubusercontent.com/35804411/125885907-9f502b22-18ae-46a2-88be-84bcffb59da1.png)

**Comment by handsomeji** [comment]
测试没有问题
