### ISSUE TITLE
passwall使用分流节点google商店下载一直转圈

### ISSUE THREAD

**Issue by firkerword** [Openwrt-Passwall/openwrt-passwall#1315]
宿主固件为大雕18.06，x86-64
这个问题应该五月份就发现了，之前没事。
使用分流节点google商店能搜索但是下载不了，要把网断开一下才能开始下载，如果直接选个tcp节点就没问题，其他都是默认设置。不知道本来就是这样还是什么原因，想求个答案。

**Comment by Felix2yu** [comment]
我这两个月也有这个问题无法下载应用，浏览搜索都正常。
奇怪的是配了一个服务器端，然后中转到这个节点却能下载。

**Comment by handsomeji** [comment]
是否使用了Xray CN直连规则？

**Comment by Felix2yu** [comment]
试了下，代理模式选择`防火墙列表`，可以正常下载，选择`中国列表以外`就是一直转圈 。
规则管理中`中国IP段(chnroute)`4个选项都试过了无法下载。
直连列表没有写`geoip:cn`

**Comment by sephinh** [comment]
> 是否使用了Xray CN直连规则？

确实是用了这个直连规则就有问题，直接不分流是ok的，昨晚google那个首页游戏就很明显，加载不出来

**Comment by handsomeji** [comment]
出现这种情况大概率原因是 google服务没有走代理
查看一下TCP日志是否有走代理
还有看看以下域名有没有在代理列表中
> googleapis.cn
> googleapis.com
> google.com.tw
> google.com.hk
> gstatic.com
> xn--ngstr-lra8j.com

**Comment by imace3** [comment]
采用geosite:google还是一样，gstatic.com等无代理,translate.google.com,gmail.com都无法完整打开页面。xray分流，国内是直连。只能把China的直连规则移到最低或者关闭。应该是中国IP段chnroute数据的问题。更换了别的源的数据也还是不行，包括hacklous的。
<img width="778" alt="截屏2021-07-25 上午4 26 46" src="https://user-images.githubusercontent.com/20973219/126880353-1215ec16-6ddb-4988-bdaf-7e7eea11d442.png">

**Comment by handsomeji** [comment]
![image](https://user-images.githubusercontent.com/60100640/126891485-88e5e4d0-a87f-4a23-ba09-bc27b115796b.png)
CN移到最下面

**Comment by binhe-cpu** [comment]
把cn移到最下面还是不行

**Comment by chancat87** [comment]
这个锅是加强版geo的问题，他把谷歌cn的域名划分到cn列表，虽然有cn但是时不时的在国内会被墙，被阻断，这种即在cn又在gfw列表的分类属实心累。建议你在代理site:google之前加一个规则geosite:google-cn为直连试试

**Comment by ghost** [comment]
2023遇到同样的问题。
现在的版本CN（也就是Direct）已经在最下，且repo作者贴的那几个域名也已经在代理列表了，但还是不行。
不过上面几位分析的原因应该没错，于是自己尝试了下在Proxy规则里添加：
`geosite:google@cn`
最后解决了，分享一下希望能帮助到别人。

**Comment by comanche2008** [comment]
> 2023遇到同样的问题。 现在的版本CN（也就是Direct）已经在最下，且repo作者贴的那几个域名也已经在代理列表了，但还是不行。 不过上面几位分析的原因应该没错，于是自己尝试了下在Proxy规则里添加： `geosite:google@cn` 最后解决了，分享一下希望能帮助到别人。

我用的是openclash，最近也出现了这个问题，请问在clash配置中如何设置呢

**Comment by zmcNotafraid** [comment]
![image](https://user-images.githubusercontent.com/12708910/215324060-554813e1-f46b-477d-88be-90e75d21873b.png)
我这样修改后就可以了

**Comment by comanche2008** [comment]
> ![image](https://user-images.githubusercontent.com/12708910/215324060-554813e1-f46b-477d-88be-90e75d21873b.png) 我这样修改后就可以了

我用的也是openclash，前段时间就发现在google play里无法下载更新app，但是用手机的cfw，同样的订阅就正常下载更新。认真读了一下meta的配置，把openclash的配置文件重新修改，然后发现google play可以正常下载更新app了。

**Comment by LorneMalvo110** [comment]
> 2023遇到同样的问题。 现在的版本CN（也就是Direct）已经在最下，且repo作者贴的那几个域名也已经在代理列表了，但还是不行。 不过上面几位分析的原因应该没错，于是自己尝试了下在Proxy规则里添加： `geosite:google@cn` 最后解决了，分享一下希望能帮助到别人。

请问大佬具体如何操作，我把geosite:google@cn 加入了代理列表还是不行

**Comment by bjznl** [comment]
> 

同样是2023年碰到这个问题，我是在规则列表里面新增了一个GOOGLE的项，内容写得geosite:google-cn  和geosite:google@cn，顺序排在CHINA前面，随便选一个代理。

**Comment by firkerword** [comment]
> 同样是2023年碰到这个问题，我是在规则列表里面新增了一个GOOGLE的项，内容写得geosite:google-cn 和geosite:google@cn，顺序排在CHINA前面，随便选一个代理。

我是直接把代理列表全删了，目前可以正常下载

**Comment by baodp** [comment]
我现在也遇到这个问题最新版本。
![Uploading 微信图片_20230304140
<img width="725" alt="微信图片_20230304140708" src="https://user-images.githubusercontent.com/32240970/222879181-1200281b-a051-408b-b9c8-bf6a64af7281.png">
659.png…]()
<img width="858" alt="微信图片_20230304140713" src="https://user-images.githubusercontent.com/32240970/222879184-0f10f4d8-ec12-47ad-86bf-240a29ffd971.png">

**Comment by baodp** [comment]
<img width="725" alt="微信图片_20230304140708" src="https://user-images.githubusercontent.com/32240970/222879191-4f499318-3ff0-4ead-83ce-5e9326ee4df9.png">

**Comment by baodp** [comment]
<img width="785" alt="微信图片_20230304140659" src="https://user-images.githubusercontent.com/32240970/222879200-98f288a3-a5e8-4b69-86c6-8070ad219378.png">

**Comment by baodp** [comment]
<img width="860" alt="微信图片_20230304140854" src="https://user-images.githubusercontent.com/32240970/222879227-24d067a7-e2d0-4953-b766-4fa8e804cdd0.png">

**Comment by woni928** [comment]
> 2023遇到同样的问题。 现在的版本CN（也就是Direct）已经在最下，且repo作者贴的那几个域名也已经在代理列表了，但还是不行。 不过上面几位分析的原因应该没错，于是自己尝试了下在Proxy规则里添加： `geosite:google@cn` 最后解决了，分享一下希望能帮助到别人。

果然如此 感谢感谢！！！

**Comment by benny856694** [comment]
> 2023遇到同样的问题。
> 现在的版本CN（也就是Direct）已经在最下，且repo作者贴的那几个域名也已经在代理列表了，但还是不行。
> 不过上面几位分析的原因应该没错，于是自己尝试了下在Proxy规则里添加：
> `geosite:google@cn`
> 最后解决了，分享一下希望能帮助到别人。

有效

**Comment by chancat87** [comment]
> 

我是直接geosite:google
