### ISSUE TITLE
编译出来的passwall.ipk文件名是版本号缺失的，建议修复下（已经这样好久了，今天忍不住issues了一下）

### ISSUE THREAD

**Issue by ghost** [Openwrt-Passwall/openwrt-passwall#1318]
![图片](https://user-images.githubusercontent.com/67452171/126025504-aa9e592a-2c36-4ea5-8626-006791c0139f.png)

**Comment by tritu** [comment]
I also noticed that yesterday

**Comment by handsomeji** [comment]
openwrt master分支正常
