### ISSUE TITLE
UDP代理（11.1.1.1）泄漏

### ISSUE THREAD

**Issue by vxmp** [Openwrt-Passwall/openwrt-passwall#1324]
这种情况自Fake IP模式开发出来后就一直存在，目前的passwall版本是4-29，服务端日志如下：
2021/07/19 21:51:09 myIP:0 accepted tcp:pagead2.googlesyndication.com:443 [block]
2021/07/19 21:51:09 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:09 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:10 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:10 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:11 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:11 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:13 myIP:0 accepted tcp:mtalk.google.com:5228 [direct]
2021/07/19 21:51:15 myIP:0 accepted tcp:youtubei.googleapis.com:443 [direct]
2021/07/19 21:51:15 myIP:0 accepted tcp:i.ytimg.com:443 [direct]
2021/07/19 21:51:16 myIP:0 accepted tcp:suggestqueries.google.com:443 [direct]
2021/07/19 21:51:17 myIP:0 accepted tcp:youtubei.googleapis.com:443 [direct]
2021/07/19 21:51:17 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:17 myIP:0 accepted tcp:redirector.googlevideo.com:443 [direct]
2021/07/19 21:51:17 myIP:0 accepted tcp:redirector.googlevideo.com:443 [direct]
2021/07/19 21:51:17 myIP:0 accepted tcp:redirector.googlevideo.com:443 [direct]
2021/07/19 21:51:18 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:18 myIP:0 accepted tcp:r3---sn-a5meknl6.googlevideo.com:443 [direct]
2021/07/19 21:51:18 myIP:0 accepted tcp:r2---sn-a5msen7l.googlevideo.com:443 [direct]
2021/07/19 21:51:18 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:19 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:19 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:19 myIP:0 accepted tcp:r6---sn-a5mekney.googlevideo.com:443 [direct]
2021/07/19 21:51:19 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:19 myIP:0 accepted tcp:r1---sn-a5meknzs.googlevideo.com:443 [direct]
2021/07/19 21:51:19 myIP:0 accepted tcp:r1---sn-a5meknzs.googlevideo.com:443 [direct]
2021/07/19 21:51:19 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:19 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:19 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:20 myIP:0 accepted tcp:r1---sn-a5meknzs.googlevideo.com:443 [direct]
2021/07/19 21:51:20 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:21 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:21 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:21 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:21 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:21 myIP:0 accepted tcp:r1---sn-a5mlrn7z.googlevideo.com:443 [direct]
2021/07/19 21:51:22 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:22 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:22 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:22 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:23 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:23 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:23 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:23 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:25 myIP:0 accepted udp:11.1.1.1:443 [block]
2021/07/19 21:51:25 myIP:0 accepted tcp:mtalk.google.com:5228 [direct]
2021/07/19 21:51:26 myIP:0 accepted tcp:mtalk.google.com:5228 [direct]
2021/07/19 21:51:28 myIP:0 accepted tcp:play.googleapis.com:443 [direct]

看u2b视频时情况特别严重，因服务端接收过多的UDP:11.1.1.1请求，一开始在iptables里添加了drop 11.1.1.1的防火墙出站过滤规则，后来发现包太多，于是就在xray config中设置blocked了。

且本地WAN口（PPPoE）也会发出11.1.1.1请求，只不过量没有被代理发向服务端的那么大，同样在本地防火墙采取了措施：
root@openwrt:/# iptables -nvL |grep 11.1.1.1
   19  1000 zone_wan_dest_DROP  all  --  *      *       0.0.0.0/0            11.1.1.1             /* !fw3: drop11.1.1.1 */

客户端配置方式：
root@openwrt:/# cat /overlay/upper/etc/config/passwall

config global
        option up_china_dns 'default'
        option loglevel 'warning'
        option trojan_loglevel '2'
        option enabled '1'
        option tcp_node '696cd32c1d5149ee95fd1b3accbad6df'
        option socks_enabled '0'
        option udp_proxy_mode 'gfwlist'
        option dns_mode 'fake_ip'
        option tcp_proxy_mode 'chnroute'
        option udp_node 'tcp'
        option localhost_tcp_proxy_mode 'default'
        option localhost_udp_proxy_mode 'default'
        option close_log_tcp '0'
        option close_log_udp '0'

config global_haproxy
        option balancing_enable '0'

config global_delay
        option auto_on '0'
        option start_delay '1'
        option start_daemon '1'

config global_forwarding
        option process '0'
        option tcp_no_redir_ports 'disable'
        option proxy_ipv6 '0'
        option accept_icmp '0'
        option tcp_redir_ports '1:65535'
        option udp_no_redir_ports 'disable'
        option udp_redir_ports '1:65535'
        option tcp_proxy_way 'tproxy'

config global_other
        option status 'big_icon show_check_port show_ip111'
        option ipv6_tproxy '0'
        option nodes_ping 'tcping info'

config global_rules
        option chnlist_update '1'
        option chnroute_update '1'
        option chnroute6_update '1'
        option gfwlist_update '1'
        option gfwlist_url 'https://cdn.jsdelivr.net/gh/Loukky/gfwlist-by-loukky/gfwlist.txt'
        option chnroute6_url 'https://ispip.clang.cn/all_cn_ipv6.txt'
        list chnlist_url 'https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf'
        list chnlist_url 'https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/apple.china.conf'
        list chnlist_url 'https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/google.china.conf'
        option xray_location_asset '/usr/share/xray/'
        option geosite_update '1'
        option geoip_update '1'
        option auto_update '1'
        option week_update '7'
        option time_update '6'
        option chnroute_url 'https://ispip.clang.cn/all_cn.txt'

config global_app
        option xray_file '/usr/bin/xray'
        option trojan_go_file '/usr/bin/trojan-go'
        option kcptun_client_file '/usr/bin/kcptun-client'
        option brook_file '/usr/bin/brook'

config global_subscribe
        option subscribe_proxy '0'
        option auto_update_subscribe '0'
        option allowInsecure '1'
        option filter_keyword_mode '1'
        list filter_discard_list '过期时间'
        list filter_discard_list '剩余流量'
        list filter_discard_list 'QQ群'
        list filter_discard_list '官网'

config auto_switch
        option testing_time '1'
        option enable '0'

config nodes '696cd32c1d5149ee95fd1b3accbad6df'
        option type 'Xray'
        option default_proxy '0'
        option protocol '_balancing'
        option domainStrategy 'AsIs'
        option remarks 'HA_tcp'
        list balancing_node '17fa59001c1749a1af8050212f030ab3'
        list balancing_node 'e1705be319b04ec0aa5c875b1f71a2a7'
        list balancing_node '79fa15198586414dbb03283c3db1b81b'
        list balancing_node 'aa43bb674eb949ab98fe450ec9871445'
        list balancing_node '9921952c832044a3baf9f8403778ec48'
        list balancing_node '1d66dc6145504edfa614fa0b3055cc6e'
        list balancing_node '25696e32c21d42afadc1ff8d964a1205'
        list balancing_node '26900939eff24497a1001d3ea966096e'

config shunt_rules 'ads'
        option remarks '广告'
        option domain_list 'geosite:category-ads'
        option protocol 'http tls bittorrent'

config shunt_rules 'China'
        option remarks 'China'
        option domain_list 'geosite:cn'
        option ip_list 'geoip:cn'

config shunt_rules 'Telegram'
        option remarks 'Telegram'
        option ip_list '149.154.160.0/20
91.108.4.0/22
91.108.56.0/24
109.239.140.0/24
67.198.55.0/24'

config shunt_rules 'youtube'
        option remarks 'youtube'
        option domain_list 'youtube
youtube.com
youtu.be
googlevideo.com
ytimg.com
gvt2.com'

config shunt_rules 'netflix'
        option remarks '奈飞'
        option domain_list 'fast.com
netflix
netflix.com
netflix.net
nflxso.net
nflxext.com
nflximg.com
nflximg.net
nflxvideo.net
netflixdnstest0.com
netflixdnstest1.com
netflixdnstest2.com
netflixdnstest3.com
netflixdnstest4.com
netflixdnstest5.com
netflixdnstest6.com
netflixdnstest7.com
netflixdnstest8.com
netflixdnstest9.com'

config shunt_rules 'TVB'
        option remarks 'TVB'
        option domain_list 'tvb.com
mytvsuper.com'

config nodes '17fa59001c1749a1af8050212f030ab3'
        option protocol 'vless'
        option encryption 'none'
        option ws_host 'myDOMAIN'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option tls '1'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '1'
        option address 'cloudflareCDNip1'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes 'e1705be319b04ec0aa5c875b1f71a2a7'
        option protocol 'vless'
        option encryption 'none'
        option ws_host 'myDOMAIN'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option tls '1'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '2'
        option address 'cloudflareCDNip2'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes '79fa15198586414dbb03283c3db1b81b'
        option ws_host 'myDOMAIN'
        option protocol 'vless'
        option encryption 'none'
        option tls '1'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '3'
        option address 'cloudflareCDNip3'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes 'aa43bb674eb949ab98fe450ec9871445'
        option protocol 'vless'
        option encryption 'none'
        option ws_host 'myDOMAIN'
        option tls '1'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '4'
        option address 'cloudflareCDNip4'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes '9921952c832044a3baf9f8403778ec48'
        option ws_host 'myDOMAIN'
        option protocol 'vless'
        option encryption 'none'
        option tls '1'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option address 'cloudflareCDNip5'
        option remarks '5'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes '1d66dc6145504edfa614fa0b3055cc6e'
        option protocol 'vless'
        option encryption 'none'
        option ws_host 'myDOMAIN'
        option tls '1'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '6'
        option address 'cloudflareCDNip6'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes '25696e32c21d42afadc1ff8d964a1205'
        option ws_host 'myDOMAIN'
        option protocol 'vless'
        option encryption 'none'
        option tls '1'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '7'
        option address 'cloudflareCDNip7'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes '26900939eff24497a1001d3ea966096e'
        option protocol 'vless'
        option encryption 'none'
        option ws_host 'myDOMAIN'
        option tls '1'
        option type 'Xray'
        option tls_serverName 'myDOMAIN'
        option port '443'
        option uuid 'myUUID'
        option xtls '0'
        option transport 'ws'
        option remarks '8'
        option address 'cloudflareCDNip8'
        option ws_path '/myPATH?ed=2048'
        option fingerprint 'chrome'
        option alpn 'http/1.1'

config nodes 'acee937d29f94d3ca8677e7b9f7cf0e6'
        option remarks 'HA_udp'
        option type 'Xray'
        option protocol '_balancing'
        option domainStrategy 'AsIs'
        list balancing_node '25696e32c21d42afadc1ff8d964a1205'
        list balancing_node '26900939eff24497a1001d3ea966096e'

不知道这算不算问题，在此特别感谢各位大神的辛劳付出。

**Comment by handsomeji** [comment]
新版已经remove这个模式，以后将会用xray内置的fakedns代替。
