### ISSUE TITLE
指定alpn后依然无法使用gRPC

### ISSUE THREAD

**Issue by CC-3301** [Openwrt-Passwall/openwrt-passwall#1326]
最近编译升级后发现多出了指定alpn选项，很是惊喜，感谢大佬的付出！
不过设定alpn为h2,http/1.1或者单h2还是无法使用gRPC，换为ShadowsocksR Plus+后正常
麻烦有识之士帮忙看看是哪里出了问题

使用的一键脚本
https://github.com/kirin10000/Xray-script

xray服务端配置

{
    "log": {
        "loglevel": "none"
    },
    "inbounds": [
        {
            "port": 443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid",
                        "flow": "xtls-rprx-direct"
                    }
                ],
                "decryption": "none",
                "fallbacks": [
                    {
                        "path": "/ecb4f50",
                        "dest": "@/dev/shm/xray/ws.sock"
                    },
                    {
                        "alpn": "h2",
                        "dest": "/dev/shm/nginx_unixsocket/h2.sock"
                    },
                    {
                        "dest": "/dev/shm/nginx_unixsocket/default.sock"
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "xtls",
                "xtlsSettings": {
                    "alpn": [
                        "h2",
                        "http/1.1"
                    ],
                    "minVersion": "1.2",
                    "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                    "certificates": [
                        {
                            "certificateFile": "/usr/local/nginx/certs/域名.cer",
                            "keyFile": "/usr/local/nginx/certs/域名.key",
                            "ocspStapling": 3600
                        }
                    ]
                }
            }
        },
        {
            "listen": "/dev/shm/xray_unixsocket/grpc.sock",
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "uuid"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "4b5ef2c"
                }
            }
        },
        {
            "listen": "@/dev/shm/xray/ws.sock",
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "uuid"
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "path": "/ecb4f50"
                }
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}

nginx配置(/usr/local/nginx/conf/nginx.conf)

user  root root;
worker_processes  auto;

google_perftools_profiles /dev/shm/nginx_tcmalloc/tcmalloc;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    include       /usr/local/nginx/conf.d/xray.conf;
}

nginx配置(/usr/local/nginx/conf.d/xray.conf)

server {
    listen 80 reuseport default_server;
    listen [::]:80 reuseport default_server;
    return 301 https://域名;
}
server {
    listen 80;
    listen [::]:80;
    server_name 域名;
    return 301 https://$host$request_uri;
}
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock default_server;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2 default_server;
    return 301 https://域名;
}
server {
    listen unix:/dev/shm/nginx_unixsocket/default.sock;
    listen unix:/dev/shm/nginx_unixsocket/h2.sock http2;
    server_name 域名;
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
    location = /4b5ef2c/TunMulti {
        grpc_pass grpc://unix:/dev/shm/xray_unixsocket/grpc.sock;
    }
    location / {
        proxy_set_header X-Forwarded-For 127.0.0.1;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://unix:/dev/shm/cloudreve_unixsocket/cloudreve.sock;
        client_max_body_size 0;
    }
}
#-----------------不要修改以下内容----------------
#domain_list=域名
#true_domain_list=域名
#domain_config_list=2
#pretend_list=1

**Comment by jh0072110** [comment]
目前grpc会睡死不太建议日常使用…（有解决方式pr不过r大尚未合并…）

**Comment by lxhao61** [comment]
> 最近编译升级后发现多出了指定alpn选项，很是惊喜，感谢大佬的付出！
> 不过设定alpn为h2,http/1.1或者单h2还是无法使用gRPC，换为ShadowsocksR Plus+后正常
> 麻烦有识之士帮忙看看是哪里出了问题
> 
> 使用的一键脚本
> https://github.com/kirin10000/Xray-script
> 
> xray服务端配置
> 
> {
> "log": {
> "loglevel": "none"
> },
> "inbounds": [
> {
> "port": 443,
> "protocol": "vless",
> "settings": {
> "clients": [
> {
> "id": "uuid",
> "flow": "xtls-rprx-direct"
> }
> ],
> "decryption": "none",
> "fallbacks": [
> {
> "path": "/ecb4f50",
> "dest": "@/dev/shm/xray/ws.sock"
> },
> {
> "alpn": "h2",
> "dest": "/dev/shm/nginx_unixsocket/h2.sock"
> },
> {
> "dest": "/dev/shm/nginx_unixsocket/default.sock"
> }
> ]
> },
> "streamSettings": {
> "network": "tcp",
> "security": "xtls",
> "xtlsSettings": {
> "alpn": [
> "h2",
> "http/1.1"
> ],
> "minVersion": "1.2",
> "cipherSuites": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
> "certificates": [
> {
> "certificateFile": "/usr/local/nginx/certs/域名.cer",
> "keyFile": "/usr/local/nginx/certs/域名.key",
> "ocspStapling": 3600
> }
> ]
> }
> }
> },
> {
> "listen": "/dev/shm/xray_unixsocket/grpc.sock",
> "protocol": "vless",
> "settings": {
> "clients": [
> {
> "id": "uuid"
> }
> ],
> "decryption": "none"
> },
> "streamSettings": {
> "network": "grpc",
> "grpcSettings": {
> "serviceName": "4b5ef2c"
> }
> }
> },
> {
> "listen": "@/dev/shm/xray/ws.sock",
> "protocol": "vmess",
> "settings": {
> "clients": [
> {
> "id": "uuid"
> }
> ]
> },
> "streamSettings": {
> "network": "ws",
> "wsSettings": {
> "path": "/ecb4f50"
> }
> }
> }
> ],
> "outbounds": [
> {
> "protocol": "freedom"
> }
> ]
> }
> 
> nginx配置(/usr/local/nginx/conf/nginx.conf)
> 
> user root root;
> worker_processes auto;
> 
> google_perftools_profiles /dev/shm/nginx_tcmalloc/tcmalloc;
> 
> events {
> worker_connections 1024;
> }
> 
> http {
> include mime.types;
> default_type application/octet-stream;
> 
> ```
> sendfile        on;
> 
> keepalive_timeout  65;
> 
> include       /usr/local/nginx/conf.d/xray.conf;
> ```
> 
> }
> 
> nginx配置(/usr/local/nginx/conf.d/xray.conf)
> 
> server {
> listen 80 reuseport default_server;
> listen [::]:80 reuseport default_server;
> return 301 [https://域名](https://%E5%9F%9F%E5%90%8D);
> }
> server {
> listen 80;
> listen [::]:80;
> server_name 域名;
> return 301 https://$host$request_uri;
> }
> server {
> listen unix:/dev/shm/nginx_unixsocket/default.sock default_server;
> listen unix:/dev/shm/nginx_unixsocket/h2.sock http2 default_server;
> return 301 [https://域名](https://%E5%9F%9F%E5%90%8D);
> }
> server {
> listen unix:/dev/shm/nginx_unixsocket/default.sock;
> listen unix:/dev/shm/nginx_unixsocket/h2.sock http2;
> server_name 域名;
> add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
> location = /4b5ef2c/TunMulti {
> grpc_pass grpc://unix:/dev/shm/xray_unixsocket/grpc.sock;
> }
> location / {
> proxy_set_header X-Forwarded-For 127.0.0.1;
> proxy_set_header Host $http_host;
> proxy_redirect off;
> proxy_pass http://unix:/dev/shm/cloudreve_unixsocket/cloudreve.sock;
> client_max_body_size 0;
> }
> }
> #-----------------不要修改以下内容----------------
> #domain_list=域名
> #true_domain_list=域名
> #domain_config_list=2
> #pretend_list=1

nginx配置错误。gRPC反代只能工作在http/2中，WebSocket反代工作在http/1.1中，http/1.1与http/2配置必须分开。
另外既然有回落模式，建议WebSocket回落分流，不必反代。
可参考示例：https://github.com/lxhao61/integrated-examples
