### ISSUE TITLE
4.29版本使用一段时间后，出现Too many open files的问题，导致不可用

### ISSUE THREAD

**Issue by naturecurly** [Openwrt-Passwall/openwrt-passwall#1327]
暂时退回4.26版本

**Comment by Myoko** [comment]
没有发现这个问题

**Comment by yaott2020-666** [comment]
我也有这个问题，一开始一切正常，但是由于kmod-br-netfilter这个软件包与xray的fullcone冲突，就卸载了，重启之后就间歇性连不上。

**Comment by handsomeji** [comment]
不能保留配置升级

**Comment by naturecurly** [comment]
@xiaorouji 我删除了老的passwall的配置文件用新的，还是会出现这个问题。

**Comment by lxhao61** [comment]
没有发现这个问题，[仅这个更新后，luic界面卡死及断开。回退上一个更新，卡死问题解决。](https://github.com/xiaorouji/openwrt-passwall/commit/033670c26833c6cc6930602dd65339b6673e850d)

**Comment by yaott2020-666** [comment]
补个日志：

2021/07/21 17:35:29 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:30 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:30 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:31 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:31 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:32 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:32 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:33 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:33 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:34 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:34 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:35 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:35 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:36 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files
2021/07/21 17:35:36 [Warning] transport/internet/tcp: failed to accepted raw connections > accept tcp [::]:1041: accept4: too many open files

**Comment by naturecurly** [comment]
@yaott2020-666 看起来是太多连接没有关闭的原因

**Comment by yaott2020-666** [comment]
前几个版本没有这个问题，好像从4-29开始的

**Comment by handsomeji** [comment]
`ulimit -n 65535`

**Comment by naturecurly** [comment]
我查了下我系统默认的是395440,最大文件数应该很大了，之前版本确实没有这个问题

**Comment by yaott2020-666** [comment]
@xiaorouji 设置了也不行

**Comment by yaott2020-666** [comment]
@naturecurly 有用docker吗

**Comment by naturecurly** [comment]
@yaott2020-666 没用docker，不过我也没抓日志，已经降级了，打算等等有没有更多人反馈

**Comment by naturecurly** [comment]
@xiaorouji 
我升级到4-29之后, 用了一段时间

睡了一觉起来 就报too many open files的log

**Comment by naturecurly** [comment]
我发现启动passwall之后会创建多个xray和pdnsd的进程，这是不是也不太正常

**Comment by z104866** [comment]
折磨死我了。。。。这边也是这样的问题。。。。但是好像和节点也有关系。。。特别是我用了passwall-负载均衡之后问题特别厉害。。。

**Comment by z104866** [comment]
> 暂时退回4.26版本

兄弟如何看我现在的版本？如何退回4.26版本？

**Comment by yaott2020-666** [comment]
4-28异常，还更加厉害

**Comment by naturecurly** [comment]
@z104866 我之前编译过4.26版本，所以直接卸载passwall重新装4.26版本

**Comment by naturecurly** [comment]
@yaott2020-666 那可能是4.28版本就引入了bug？你试过4.27版本吗，可以帮助缩小一下是哪次改动导致的问题

**Comment by yaott2020-666** [comment]
还停在4-28 暂时关了

**Comment by naturecurly** [comment]
大佬更新4.30了，我看加了ulimit，虽然感觉是哪个地方泄漏了，但准备回去试试看有没有好

**Comment by z104866** [comment]
> 大佬更新4.30了，我看加了ulimit，虽然感觉是哪个地方泄漏了，但准备回去试试看有没有好

坐等你的测试结果！！ 你那里看到大佬更新的?

**Comment by yaott2020-666** [comment]
已经装上了，目前正常

**Comment by yaott2020-666** [comment]
4h 一切正常
