### ISSUE TITLE
已经设置成全局访问了，QQ的居然没有经过代理

### ISSUE THREAD

**Issue by humbass** [Openwrt-Passwall/openwrt-passwall#1336]
![image](https://user-images.githubusercontent.com/5117925/126876298-cf26c9ba-c731-4d58-b8f1-2a8755d411b4.png)

已经设置了全局模式，大部分软件都会通过passwall访问，发现很少几个软件居然还是直连的，例如QQ。

如何做到真正的全局代理呢？

**Comment by db-one** [comment]
转发设置里面 设置一下

**Comment by humbass** [comment]
![20210725-1343541](https://user-images.githubusercontent.com/5117925/126889113-90f5dfdf-cc8a-46a3-84ed-b6a7ef5688a5.png)

"高级设置"  后按如图的方式设置，依然是穿透的。

**Comment by humbass** [comment]
As a temporary solution, I disable UDP on the firewall service.
