### ISSUE TITLE
自定义dns转发，在dnsmasq规则产生时候出现错误

### ISSUE THREAD

**Issue by wykdg** [Openwrt-Passwall/openwrt-passwall#1338]
当dnsmasq存在 /xxx.com/114.114.114.114 的自定义转发的时候，
在/var/etc/dnsmasq.d下面的规则转发变成了 形如 /google.com//xxx.com/114.114.114.114
最后导致不少域名解析失败。
建议在产生的时候过滤掉一些不合理的结果。
谢谢！

**Comment by handsomeji** [comment]
试试最新源码
