### ISSUE TITLE
使用了一段时间后 (1个小时-3个小时) 访问不了网页，应该是DNS的问题

### ISSUE THREAD

**Issue by huangqingchao** [Openwrt-Passwall/openwrt-passwall#1342]
试过了几个固件版本的Openwrt，也试过自己编译。
运行起来改IP和WAN口信息，打开了 Turbo Acc 里面的 DNS 缓存，其它插件没动。
直接配置Passwall，添加节点，启用，更新规则，DNS是默认的 pdnsd （8.8.8.8），一开始用的好好的，过一段时间后访问不了网页了。手机微信，手机youtube正常，所以我觉得是DNS这方面的问题，但是想不通啥问题，不知道还要提供什么信息，希望大佬给点头绪，我在回复那里提供信息。

**Comment by CC-3301** [comment]
https://www.v2ex.com/t/788719?p=1

**Comment by huangqingchao** [comment]
> https://www.v2ex.com/t/788719?p=1

我这边是网页打不开嘛，然后DNS过滤模式换了一种，就能上了，只是打开网页开始会卡一下，挺慢的。换回 Pdnsd 就上不了，要过很长一段时间再换 Pdnsd 才可以。

**Comment by wtfr-dot** [comment]
我最初几版5.10内核的dns跟你一模一样，后来发现是将老的配置编译进去造成的，后来全新配置恢复了正常，但是偶尔还是会出现你这种现象，由于最近一直在更新编译，基本上没有超过24小时，所以没有完整测试，我没有使用turboacc，使用的smartdns

**Comment by huangqingchao** [comment]
> 我最初几版5.10内核的dns跟你一模一样，后来发现是将老的配置编译进去造成的，后来全新配置恢复了正常，但是偶尔还是会出现你这种现象，由于最近一直在更新编译，基本上没有超过24小时，所以没有完整测试，我没有使用turboacc，使用的smartdns

主要是里面又 Pdnsd 又 turboacc dns 又 dnsmasq 的，蒙蒙的不知道什么路线原理，不知道怎么调试。我 Passwall 的 DND 改为不过滤，又可以上，我不知道现在用了什么DNS了

**Comment by huangqingchao** [comment]
然后一段时间后会变得很慢，我手机还上不了了，好难...

**Comment by CC-3301** [comment]
推荐使用Adguardhome，走DOH查询

**Comment by huangqingchao** [comment]
> 推荐使用Adguardhome，走DOH查询

Adguardhome 是广告拦截的么，有没有教程发来瞄瞄，我想要教程抄作业:)
还有的就是，现在有点怀疑是不是DNS的问题了
因为之前是 软路由-交换机-2个AP，软路由带机160
现在换成
DNS 模式换成 Xray DoH （不知道是不是你前面那个DOH那个意思）
软路由-交换机-2个路由器，软路由带机下去了，感觉快了....
难道是我软路由带不起这么多么
![image](https://user-images.githubusercontent.com/19640477/127127578-efff40d2-2f66-48e3-a58c-faa189d4fe8c.png)

**Comment by xiaorouji** [comment]
用dns2socks或者xray doh，我现在其实基本不用pdnsd了

**Comment by handsomeji** [comment]
`打开了 Turbo Acc 里面的 DNS 缓存`
我不知道这个是什么东西，建议所有外置DNS全部关掉。一步一步检查问题更好

**Comment by RainCat1998** [comment]
同样遇到了这个问题，最新仍然没有解决。使用的Xray分流模式。

**Comment by RainCat1998** [comment]
所有外置DNS功能全部关掉也是这样。这几天我再观察一下抓一抓日志。

**Comment by hcym** [comment]
就是默认设置，也不会搞dns，基本稳定运行，就是偶尔cpu恒定为1，这有点纳闷😂

**Comment by wtfr-dot** [comment]
在防火墙里把自定义规则注释掉，特别是L大的固件，必须注释掉，否则就会出现开始正常，过一段时间访问不了网页的现象

**Comment by huangqingchao** [comment]
我现在就用着基于原生的固件，默认配置，DNS完全不敢动

**Comment by huangqingchao** [comment]
> 在防火墙里把自定义规则注释掉，特别是L大的固件，必须注释掉，否则就会出现开始正常，过一段时间访问不了网页的现象

比较像这种情况了

**Comment by RainCat1998** [comment]
> 在防火墙里把自定义规则注释掉，特别是L大的固件，必须注释掉，否则就会出现开始正常，过一段时间访问不了网页的现象

试了下，应该暂时稳定了。感谢！
