### ISSUE TITLE
tor无法连接

### ISSUE THREAD

**Issue by EsuRt** [Openwrt-Passwall/openwrt-passwall#1343]
更新了最近的版本后，发现tor无法连接，但是在本地使用同样的线路，设置socks代理，就能正常连接。

**Comment by handsomeji** [comment]
更新规则看看，应该是规则问题

**Comment by EsuRt** [comment]
> 更新规则看看，应该是规则问题

找到原因了，默认生成的配置文件启用了流量嗅探，会干扰tor流量，配置生成中直接改为false后就能正常使用了，但passwall设置界面中没有关闭流量嗅探的选项，希望能增加一个。
https://github.com/xiaorouji/openwrt-passwall/blob/507fd8e5451ac1e2e1fb475ead9abc3aec1c22cb/luci-app-passwall/luasrc/model/cbi/passwall/api/gen_xray.lua#L253

**Comment by handsomeji** [comment]
关闭流量嗅探将无法正常使用

**Comment by EsuRt** [comment]
> 关闭流量嗅探将无法正常使用

用下来没什么影响，因为暂时没有用到需要识别流量的功能，比如说屏蔽bt流量之类的，不知道还有其他影响吗？
