### ISSUE TITLE
7月27日编译的最新版本，系统日志中有这么一段，这个是否有影响？

### ISSUE THREAD

**Issue by lovelyOK** [Openwrt-Passwall/openwrt-passwall#1344]
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs:  * Populating IPv6 nat table
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs: Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_lan_rule'
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs: Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_lan_rule'
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs: Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_wan_rule'
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs: Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_wan_rule'
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs: Warning: fw3_ipt_rule_append(): Can't find target 'prerouting_rule'
Tue Jul 27 05:44:38 2021 daemon.notice procd: /etc/rc.d/S91ssrs: Warning: fw3_ipt_rule_append(): Can't find target 'postrouting_rule'

以上这些rule我在防火墙列表中，发现是存在的。

**Comment by handsomeji** [comment]
ssrs是什么东西？与passwall无关
