### ISSUE TITLE
可否考虑在”routing“中加入”domainMatcher“项目

### ISSUE THREAD

**Issue by 70599** [Openwrt-Passwall/openwrt-passwall#1347]
`domainMatcher`设置值为`mph`时，好像有更好的域名匹配性能。
https://www.v2fly.org/config/routing.html

文档是v2ray的，但是xray也能通过配置文件检测：
```sh
> xray run -c /path/to/test.json -test
> Xray 1.4.2 (Xray, Penetrates Everything.) OpenWrt (go1.16.6 linux/arm)
A unified platform for anti-censorship.
2021/07/27 18:08:46 [Info] infra/conf/serial: Reading config: /path/to/test.json
Configuration OK.
```

还没有测试过性能变化。

**Comment by handsomeji** [comment]
我不清楚此选项能否用于透明代理环境下

**Comment by vxmp** [comment]
xray文档虽然没写，但 https://github.com/XTLS/AnXray 这个客户端导出的json配置里面是包含了"domainMatcher": "mph"字段的。是不是彩蛋？^_^

**Comment by 70599** [comment]
不报错的话，应该至少不会有减益吧

**Comment by vxmp** [comment]
我在xray4magisk的配置里加了这个字段，体验上无感，留着吧。

**Comment by handsomeji** [comment]
4.35已默认使用`mph`/`hybrid`模式
