### ISSUE TITLE
有个特殊的ss节点

### ISSUE THREAD

**Issue by ghost** [Openwrt-Passwall/openwrt-passwall#1350]
大佬，有个ss节点，passwall添加了不能使用，这个能麻烦看看吗，这个节点，目前只有Netch这个软件和iOS最新2.1.87版本才能使用，节点我能发到这里吗

**Comment by handsomeji** [comment]
看一下TCP日志

**Comment by ghost** [comment]
我还是直接发节点吧ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5NThjNmUwODJhZjM5YjQ1MWUxNjU2Yjg3NjYwYTM2M2M4OTA3MWEyMWQ1YTc2OGIxMmU1NjRkMWRiZTNlOTZl@122.9.62.45:1028/?group=#%E9%A6%99%E6%B8%AF(%E4%B8%AD%E5%9B%BD)-21%5BSVIP%5D%5BWhatsApp%5D%5BLineApp%5D

**Comment by ghost** [comment]
这个目前只能在Netch这个软件用，其他没有一个代理软件可以使用，不知道是不是有啥新规则新类型

**Comment by handsomeji** [comment]
建议换节点

**Comment by ghost** [comment]
额😓，这么尴尬吗

**Comment by w311ang** [comment]
应该是节点备注造成的，对URL编码不支持？删去特殊字符之后就可以导入了
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5NThjNmUwODJhZjM5YjQ1MWUxNjU2Yjg3NjYwYTM2M2M4OTA3MWEyMWQ1YTc2OGIxMmU1NjRkMWRiZTNlOTZl@122.9.62.45:1028#test

**Comment by w311ang** [comment]
> 应该是节点备注造成的，对URL编码不支持？删去特殊字符之后就可以导入了
> ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo5NThjNmUwODJhZjM5YjQ1MWUxNjU2Yjg3NjYwYTM2M2M4OTA3MWEyMWQ1YTc2OGIxMmU1NjRkMWRiZTNlOTZl@122.9.62.45:1028#test

有特殊字符也能导入那我错了，不过我手机shadowsocks也连不上

**Comment by ghost** [comment]
iOS的火箭吗，需要升级2.1.87才可以链接的上，安卓的话也需要特殊修改版本才可以，我看了看火箭更新日志是这个
* add shadowsocks key exchange supports
* * fix gfwpress memory leak issue
* * fix dummy ipv6 ip issue

**Comment by ghost** [comment]
因为这个也是跟火箭作者反馈了下，然后更新才能用，日志就是这个了，我也不知道啥意思😳

**Comment by w311ang** [comment]
我用的是安卓从play商店下载的ss，上次更新也是7月5日了

**Comment by ghost** [comment]
我有个特殊修改版本的，可以用，我怎么发上来呢

**Comment by xiaodan01** [comment]
https://super-xiaodan01.lanzoui.com/iwQTHs8bawj，你试试这个，就能链接

**Comment by w311ang** [comment]
看起来好像是旧版了，不过的确是可以连接
![Screenshot_20210804-190910](https://user-images.githubusercontent.com/30381083/128171061-1bf61597-fb29-4be9-8480-6a5fa0aa574f.jpg)

**Comment by ghost** [comment]
这个也是他们给我的，说是修改版，我也不知道改没改，我导入到op的ssrplus它显示是新类型的，也是连不上

**Comment by xiaodan01** [comment]
![Uploading DD71A830-82B4-497A-ACB9-012501BC8203.jpeg…]()

**Comment by w311ang** [comment]
那就只能同[楼上](#issuecomment-890474447)了

**Comment by ghost** [comment]
好吧😥

**Comment by w311ang** [comment]
也许可以考虑给shadowsocks-libev提issue？

**Comment by w311ang** [comment]
毕竟底层是它，它更新了应该都可以跟进？

**Comment by ghost** [comment]
地址是啥，我去反馈下

**Comment by w311ang** [comment]
https://github.com/shadowsocks/shadowsocks-libev

xiaodan01 ***@***.***> 于 2021年8月4日周三 下午7:22写道：

**Comment by ghost** [comment]
好的

**Comment by ghost** [comment]
我问了问iOS小火箭作者修复了点啥，他给我回复了个网址，https://github.com/SFight/ShadowPathDemo

**Comment by w311ang** [comment]
https://developer.apple.com/documentation/quartzcore/calayer/1410771-shadowpath
阴影路径？这跟无法连接无关吧

xiaodan01 ***@***.***> 于 2021年8月4日周三 下午8:38写道：
