### ISSUE TITLE
passwall启用后，PC端访问网页速度相对而言有点慢

### ISSUE THREAD

**Issue by lovelyOK** [Openwrt-Passwall/openwrt-passwall#1351]
存粹反馈情况，并非缸径！
我op上最早用的是SSRP使用一切正常，最近几个月个别V2RAY+WS+TLS节点经常有波动，所以尝试使用HA的负载均衡，但是SSRP和负载均衡结合总是跑不起来（也有可能是我没编译正确，OP最新固件5.4和5.10都尝试了），所以后来目光瞄向PASSWALL。

实际使用了1个月左右，不管我尝试了：
1、挂负载均衡还是不挂负载均衡；
2、直接使用节点；
3、使用分流节点策略；
4、关于DNS，Pdnst通过TCP请求dns，通过UDP请求DNS；
结果就是“打开网页有点慢”，哦，之前使用fake IP模式下倒是反应挺快了，但是经常性GIT CLONE下不了资料。

同样的节点放在SSRP上使用就很正常（使用PDNST请求DNS）。

**Comment by handsomeji** [comment]
那你试试用dns2socks

**Comment by lovelyOK** [comment]
> 那你试试用dns2socks

有效果，速度一下子流畅了。
