### ISSUE TITLE
使用passwall后无法访问国内网站

### ISSUE THREAD

**Issue by 54601** [Openwrt-Passwall/openwrt-passwall#1356]
我遇到一个很诡异的问题，在我设置好旁路由passwall之后：
有线连接的电脑可以正常打开国内外网页
无线连接5Gwifi的笔记本可以正常打开国内外网页
无线连接5Gwifi的手机（3台，都是iPhone），只能打开国外网页，打不开国内网页；把wifi切换成2.4G后可以正常打开国内外网页。
我尝试调整了一些dns设置，但是似乎都只影响到了手机，电脑和笔记本始终可以正常打开国内外网页，而手机在连接5G网络的情况下始终只能打开国内或国外网页。
我使用的F大的openwrt固件，passwall已更新至最新。
我们家网络拓扑图是：
光纤 - 192.168.1.1（电信SDN） - 10.0.0.1（路由器）- 10.0.0.254（旁路由）
其中，旁路由ip固定为10.0.0.254，网关指向10.0.0.1，dns设置8.8.8.8，关闭ipv6，打开强制dhcp服务。其余设置均为默认。
我还尝试过自定义dns并指向smartdns，但是也没什么用。
这个问题真是太诡异了，求大佬解答帮助。

**Comment by hcym** [comment]
单口最好用vlan，什么毛病没有，我现在有两个双口机也用单臂，省得换AP

**Comment by handsomeji** [comment]
`dns设置8.8.8.8` 这个8.8.8.8是“旁路由”LAN接口的DNS？？？

**Comment by 54601** [comment]
> `dns设置8.8.8.8` 这个8.8.8.8是“旁路由”LAN接口的DNS？？？

是的，不能这么设置吗……drl我看的教程上没提我就按原来的填了

**Comment by handsomeji** [comment]
你这样设置 DNS全跑国外去了，当然国内就有问题或者超慢

**Comment by handsomeji** [comment]
把所有的外置DNS全部关掉，DHCP/DNS里面的DNS 转发设置为空，LAN口参考我这样设置
![image](https://user-images.githubusercontent.com/60100640/127764256-ee054d4b-c2b2-42c3-aadb-5088cddedb6c.png)
然后重启

**Comment by handsomeji** [comment]
更不需要配置什么乱七八糟的iptables规则

**Comment by 54601** [comment]
> 更不需要配置什么乱七八糟的iptables规则

谢谢大佬！回家试试！
