### ISSUE TITLE
能否在未来的某个时点，在规则管理中项目添加多个URL更新合并的处理

### ISSUE THREAD

**Issue by SakuraFallingMad** [Openwrt-Passwall/openwrt-passwall#1364]
![image](https://user-images.githubusercontent.com/31793080/127987283-f261372a-deb2-47fb-bc15-39b4cc74838a.png)

现在已经有很多的一些规则在都有分享，可以考虑未来添加功能时，添加个多个规则一同更新合并处理。现在Chnlist已经有了。

**Comment by SakuraFallingMad** [comment]
比如gfwlist：https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt 和 https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/greatfire.txt 这样互补挺好的

**Comment by handsomeji** [comment]
试试最新源码，山石大佬已经做支持了

**Comment by SakuraFallingMad** [comment]
有时间试试，感谢各位大大们了，祝未来更佳美好
