### ISSUE TITLE
使用自定义DNS后Chinadns-NG失效

### ISSUE THREAD

**Issue by CC-3301** [Openwrt-Passwall/openwrt-passwall#1366]
![chinadns-ng enable](https://user-images.githubusercontent.com/38343280/128033680-bce0898b-8235-494c-bb13-0308c385a183.png)
![chinadns-ng disable](https://user-images.githubusercontent.com/38343280/128033691-6e3c8ecf-0cc4-4f1b-9f88-bcc0f01c0af9.png)

**Comment by CC-3301** [comment]
![image](https://user-images.githubusercontent.com/38343280/128037435-6e2fdf79-53b7-4764-8d16-ac480fa5a2ac.png)
请问这两个选项有什么区别吗 我发现使用UDP节点就可以启动ChinaDNS-NG 自定义的那个选项就不行

**Comment by handsomeji** [comment]
自定义DNS，顾名思义就是“自定义”

**Comment by handsomeji** [comment]
逻辑上本意是，通过UDP节点请求DNS，但是会套用ChinaDNS-NG。但是也可以偷换概念使用。。。而自定义DNS是不会套用ChinaDNS-NG的。

**Comment by lovelyOK** [comment]
使用ChinaDNS-NG+中国以外代理，和不使用ChinaDNS-NG+中国以外代理
这两者有什么区别？识别的更快？
