### ISSUE TITLE
严重Bug（难道只有我一人…）

### ISSUE THREAD

**Issue by jh0072110** [Openwrt-Passwall/openwrt-passwall#1368]
使用最新源码编译使用一段时间后会出现：
1.无法增减节点
2.无法开关psw
3.无法切换节点
的情况，重启路由也没用…
不是只有我一个人遇到这情况吧…编译了好几个版本固件/重置过软路由，一开始正常用一阵就会100%复现这个问题……

**Comment by jh0072110** [comment]
=。=甚至无法reset_config……

**Comment by SakuraFallingMad** [comment]
这是你空间满了吧。。。你其他组件有啥日志开着吧，比如adguard home。。。日志文件可不是挂载在/tmp

**Comment by handsomeji** [comment]
看看空间是不是不够了

**Comment by jh0072110** [comment]
![image](https://user-images.githubusercontent.com/50496854/128290170-fb739e05-f1f1-42e9-aecd-c036d1f8dd3c.png)

**Comment by jh0072110** [comment]
好像是我的问题，先关了=。=

**Comment by jh0072110** [comment]
好像是规则文件太大了…一更新规则瞬间干满……

**Comment by handsomeji** [comment]
geoip的问题

**Comment by jh0072110** [comment]
> geoip的问题

我发现了，所以默默给overlay扩容了，默认编译的overlay空间有点mini😅

**Comment by handsomeji** [comment]
突然由5M变成接近48M 我也懵了
