### ISSUE TITLE
trojan-go电脑和手机均可通过相应客户端连接翻墙,但passwall运行报错，请达人指点下

### ISSUE THREAD

**Issue by petraklux** [Openwrt-Passwall/openwrt-passwall#1370]
服务器端trojan-go配置好，电脑和手机均可通过相应客户端连接翻墙。
但openwrt（21.02及19.06）上编译的passwall使用trojan-go却无法翻墙。但使用xray翻墙则一切正常。
报错信息：
[INFO] 2021/08/06 01:42:07 trojan-go 0.10.4 initializing
[ERROR] 2021/08/06 01:42:11 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:112 proxy failed to dial packet | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message
[ERROR] 2021/08/06 01:42:11 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:112 proxy failed to dial packet | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message
[ERROR] 2021/08/06 01:42:12 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message
[ERROR] 2021/08/06 01:42:12 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message
[ERROR] 2021/08/06 01:42:12 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message
[ERROR] 2021/08/06 01:42:12 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message
[ERROR] 2021/08/06 01:42:12 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | websocket cannot dial with underlying client | tls failed to handshake with remote server | local error: tls: unexpected message

但使用xray的连接则一切正常。

**Comment by handsomeji** [comment]
tls failed to handshake with remote server.
检查下tls证书？允许不安全连接试试？

**Comment by petraklux** [comment]
> tls failed to handshake with remote server.
> 检查下tls证书？允许不安全连接试试？

试过了，同样不行

**Comment by handsomeji** [comment]
能否发一下服务端配置

**Comment by petraklux** [comment]
> 能否发一下服务端配置

{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 8443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "log_level": 2,
    "password": [
        "password"
    ],
    "ssl": {
        "cert": "/root/cert/cert.crt",
        "key": "/root/cert/private.key",
        "sni": "mydomain.com",
        "fallback_port": 3000
    },
    "websocket": {
    "enabled": true,
    "path": "/your-websocket-path",
    "host": "mydomain.com"
    }，
    "router":{
        "enabled": true,
        "block": [
            "geoip:private"
        ]
    }
}

**Comment by handsomeji** [comment]
测试了一下没问题

**Comment by petraklux** [comment]
解决问题了，在配置里应勾选TLS选项，指纹伪造选项与服务器端保持一致。不安全连接不需要勾选。

**Comment by chr09670** [comment]
运行不起来大多是config配置没写对的问题。去trojan-go的说明文档里看一下完整版配置的默认值是啥，再回来照着配上就可以了。
