### ISSUE TITLE
负载均衡在节点订阅后失效

### ISSUE THREAD

**Issue by cat00fish** [Openwrt-Passwall/openwrt-passwall#1371]
设置好负载均衡，运行正常。但是节点订阅更新后，负载均衡失效，不运行，负载均衡里面设置的节点列表名称都变成hasn码。
这时改用单个节点，可以使用。
但负载均衡里节点列表的节点删除不了，不能保存，提示：missing    小提示里的恢复默认配置链接也失效
overlay有15G，应该不是空间满了的原因

**Comment by hcym** [comment]
这一块尽量保持不动，数量超过10个排序就乱，节点列表操作肯定导致负载均衡异常，何况订阅那么大动静

**Comment by cat00fish** [comment]
好像是找到了原因：在节点列表里增设好负载均衡后，负载均衡这个自添“节点”在在节点列表的底部（最后1个），正常使用。但是，订阅更新时，负载均衡这个“节点”的排序自动上移到了第2位，造成订阅节点的排序整体全部错位一行，负载均衡由此失效。

如果能够有一个自添节点自动“置尾”的机制，也许可以解决。

**Comment by handsomeji** [comment]
`missing 小提示里的恢复默认配置链接也失效`
你这是后装的ipk吧

**Comment by cat00fish** [comment]
是的，是个slim版固件，但是也试过编译在固件里的，负载均衡有同样的问题
