### ISSUE TITLE
Lean+Passwall+HAproxy 导致无法上网

### ISSUE THREAD

**Issue by z104866** [Openwrt-Passwall/openwrt-passwall#1375]
和lean大神的最新源码结合才有问题 与lienol大神的最新源码就没有问题
1. 开启ha proxy 用xray vless之后一切正常
2. 开启ha proxy 用trojan 或者vmess 之后就无法访问任何网站
3. 无论哪种协议 只要开启ha proxy 之后 重新启动路由器 所有网页无法访问
4. 这个问题似乎从4.31，4.32都有一样的问题

**Comment by z104866** [comment]
似乎稳定在DNS/DHCP上面，一旦DHCP里面设置的跟据MAC绑定固定IP...就会导致无法上网

**Comment by hcym** [comment]
说没有问题，也可以说有问题，大雕的是最新版，不能用luci控制开关，pass内置的负载均衡不受影响可以用，我是用的旧版haproxy，这样luci app也可以用
