### ISSUE TITLE
Brook使用问题

### ISSUE THREAD

**Issue by tporwx** [Openwrt-Passwall/openwrt-passwall#1376]
切换brook节点会大概率出现tcp和udp未运行，切换主开关才会大概率恢复正常运行，小概率需要切换主开关多次才行。

**Comment by handsomeji** [comment]
TCP日志发一下
地址是否是域名？

**Comment by tporwx** [comment]
TCP日志打不开？
地址是域名

**Comment by handsomeji** [comment]
估计是brook启动的时候会解析域名，但是解析超时了，就直接exit了
试试改成ip连接

**Comment by tporwx** [comment]
换用ip地址后正常，不过日志还是打不开

**Comment by handsomeji** [comment]
因为启动brook时未加 --debug
