### ISSUE TITLE
搭配Lienol/openwrt-main编译，疑似passwall下trojan-plus报错

### ISSUE THREAD

**Issue by ghost** [Openwrt-Passwall/openwrt-passwall#1381]
![图片](https://user-images.githubusercontent.com/67452171/128673654-d4bd48ec-624f-490c-8205-c1ed62528241.png)
Lienol/openwrt-main为主体进行编译，passwall下所有依赖都勾选的，编译到如图这里trojan-plus报错。请问如何解决，是BUG吗还是我编译不应该勾选和trojan-plus冲突的什么依赖吗？

**Comment by handsomeji** [comment]
看不出哪里有问题
-j1 了吗

**Comment by ghost** [comment]
> 
> 
> 看不出哪里有问题
> -j1 了吗

刚才pull了更新代码，又跑一遍成功了。。打扰了，谢谢前面回复。（没用-j1）
