### ISSUE TITLE
用着用着界面乱了，上不了网

### ISSUE THREAD

**Issue by lafVinson** [Openwrt-Passwall/openwrt-passwall#1384]
我的用着用着突然就不好用了，重装了但是还是不好用。请问这是怎么回事呢。 之前用的好好的，一直都没问题，今天突然就不好用了。上不了网，界面也乱了，很多按钮都没了，显示尚无任何配置，请问大神这是咋回事，谢谢

**Comment by handsomeji** [comment]
空间满了
