### ISSUE TITLE
反馈一个不知算不算BUG的细节

### ISSUE THREAD

**Issue by ghost** [Openwrt-Passwall/openwrt-passwall#1385]
![图片](https://user-images.githubusercontent.com/67452171/128816789-c890087d-3f18-479a-b000-fdc248c66576.png)
如图，编译出来的ipk，passwall没有版本号了，4后面是空的。一直都这样有快一个月了吧感觉。

**Comment by handsomeji** [comment]
我编译出来是有的

**Comment by OSSBoy** [comment]
![Screenshot from 2021-08-11 11-29-42](https://user-images.githubusercontent.com/4075793/128965335-781663a4-ae92-46e0-b43b-a42f5dae6ad3.png)
我这里也是只有4，我编译的是官方openwrt21.02。

**Comment by boduoyejieyi666** [comment]
果然楼上和我一样。。。我是用的Lienol/OpenWrt的main分支

**Comment by ghost** [comment]
果然楼上和我一样。。。我是用的Lienol/OpenWrt的main分支

**Comment by handsomeji** [comment]
似乎是新版luci修改了点东西，下个版本改一下
