### ISSUE TITLE
为什么导入连接一直无效？或者修改原节点任何信息都无法连接上？

### ISSUE THREAD

**Issue by crazynet999** [Openwrt-Passwall/openwrt-passwall#1388]
几个情况：
1、使用原配置可以上；原配置复制节点，命名不同名字，其余任何信息不变化，无法连接上。
2、通过连接添加、手动添加节点均无法连接上；
3、尝试重装passwall、编译新固件，均无法解决；
4、以上问题不是DNS问题，不是节点问题，电脑、手机相同配置均可以上
5、仅仅是我个人碰到？

**Comment by handsomeji** [comment]
节点类型？
节点URL链接？
TCP日志？
逻辑日志？

**Comment by bg4dew** [comment]
节点URL链接导入连不上，同样导入到v2rayN可以正常使用

**Comment by crazynet999** [comment]
节点类型：v2ray
URL链接：手动或者v2rayN 通过链接分享导入
TCP日志: 同一节点/同一配置情况下

V2Ray 4.41.1 (V2Fly, a community-driven edition of V2Ray.) OpenWrt (go1.16.6 linux/amd64)
A unified platform for anti-censorship.
2021/08/12 02:29:58 [Info] main/jsonem: Reading config: /var/etc/passwall/TCP.json
2021/08/12 02:29:58 [Warning] V2Ray 4.41.1 started
2021/08/12 02:30:02 59.XX.XXX.XXX:45042 accepted tcp:192.64.119.255:80 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:02 59.XX.XXX.XXX:45044 accepted tcp:192.64.119.255:80 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:09 59.XX.XXX.XXX:33419 accepted tcp:8.8.8.8:53 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:09 59.XX.XXX.XXX:9385 accepted tcp:8.8.8.8:53 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:10 59.XX.XXX.XXX:54052 accepted tcp:XXX域名XXX:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:11 10.10.1.70:34622 accepted tcp:216.58.200.234:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:14 59.XX.XXX.XXX:54762 accepted tcp:8.8.8.8:53 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:16 59.XX.XXX.XXX:54064 accepted tcp:XXX域名XXX:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:18 59.XX.XXX.XXX:54068 accepted tcp:XXX域名XXX:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:20 59.XX.XXX.XXX:54072 accepted tcp:XXX域名XXX:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:30:21 59.XX.XXX.XXX:54076 accepted tcp:XXX域名XXX:443 [f3ccf95f19f24d6abcf0bab2290579f7]
__________以上是正常访问的_____________


__________以下是上面的节点,随便更改一个名字(停止后-修改节点名字后保存,启动的日志)_____________
V2Ray 4.41.1 (V2Fly, a community-driven edition of V2Ray.) OpenWrt (go1.16.6 linux/amd64)
A unified platform for anti-censorship.
2021/08/12 02:31:26 [Info] main/jsonem: Reading config: /var/etc/passwall/TCP.json
2021/08/12 02:31:26 [Warning] V2Ray 4.41.1 started
2021/08/12 02:31:29 10.10.1.70:60610 accepted tcp:172.217.24.10:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:31:35 [Warning] [3106561899] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > unexpected EOF transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00" transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > unexpected EOF] > common/retry: all retry attempts failed
2021/08/12 02:31:35 10.10.1.70:60622 accepted tcp:172.217.24.10:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:31:37 59.XX.XXX.XXX:12925 accepted tcp:8.8.8.8:53 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:31:37 59.XX.XXX.XXX:46618 accepted tcp:8.8.8.8:53 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:31:38 [Warning] [930703772] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > unexpected EOF transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00" transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > unexpected EOF] > common/retry: all retry attempts failed
2021/08/12 02:31:38 10.10.1.70:60624 accepted tcp:172.217.24.10:443 [f3ccf95f19f24d6abcf0bab2290579f7]
2021/08/12 02:31:40 [Warning] [1529329399] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXX域名XXX.xyz/ray): > unexpected EOF] > common/retry: all retry attempts failed
2021/08/12 02:31:40 59.XX.XXX.XXX:65114 accepted tcp:8.8.8.8:53 [f3ccf95f19f24d6abcf0bab2290579f7]

**Comment by crazynet999** [comment]
补充：ss节点一切正常，没问题

**Comment by xiaorouji** [comment]
@crazynet999 可以发一下链接到我邮箱让我测试吗？
xiaoroujixxoo@gmail.com

**Comment by handsomeji** [comment]
alpn选http1.1
