### ISSUE TITLE
[小bug]Hysteria节点检测失败 但百度谷歌连接正常

### ISSUE THREAD

**Issue by CC-3301** [Openwrt-Passwall/openwrt-passwall#1389]
![image](https://user-images.githubusercontent.com/38343280/128880839-d3adc0c3-a5d6-44b2-9c61-1b07fc6e5ec1.png)

**Comment by handsomeji** [comment]
Hysteria基于QUIC，不支持TCP检测

**Comment by CC-3301** [comment]
收到，学习了，谢大佬
