### ISSUE TITLE
海龟回国模式

### ISSUE THREAD

**Issue by jacky441** [Openwrt-Passwall/openwrt-passwall#1392]
很久没有玩openwrt了  近期的版本怎么没有回国模式了？ 因为老的软路由 系统问题。。需要重装
还是现在都用别的 方法了？

**Comment by yaott2020-666** [comment]
中国列表不就是吗

**Comment by jacky441** [comment]
只有“中国列表以外“  是用这个？  好像用了但是好像是类似全局模式。。。

**Comment by yaott2020-666** [comment]
最新的源码编译出来有，不行可以试试看xray的自定义分流，你想怎么分就怎么分

**Comment by handsomeji** [comment]
![image](https://user-images.githubusercontent.com/60100640/129058549-e1ee8f98-a70c-476f-8d2d-143b74b74460.png)
