### ISSUE TITLE
关于获取外网IPv6的问题,烦请开发者解答下

### ISSUE THREAD

**Issue by Lee917** [Openwrt-Passwall/openwrt-passwall#1394]
请问怎样解决PassWall无法获取到VPS的IPv6地址的问题？
我开启PassWall无法获取到VPS上的IPv6地址,关闭PassWall后，再打开手机上的V2rayNG，是可以获取到VPS的IPv6的.
开启PassWall:
![photo_2021-08-12_10-16-56](https://user-images.githubusercontent.com/25250112/129135874-9ceae7c4-a1c0-47ee-9bfe-7d26590bd2f2.jpg)

关闭PassWall后,打开手机上的V2rayNG(请注意上方状态栏的钥匙图标):
![photo_2021-08-12_10-16-54](https://user-images.githubusercontent.com/25250112/129135884-fad0fabd-5615-41d5-bb4e-95db86cc828a.jpg)

打开PassWall高级设置中的IPv6透明代理后,能获取到VPS的IPv6地址,但却出现了下图的情况(一些网站访问异常,不论国内还是国外的):
大部分网站是像这样的,打开后提示网站安全性问题,且证书变为软路由的自签证书,选择继续访问后就跳到软路由的登录界面:
![屏幕截图 2021-08-12 120840](https://user-images.githubusercontent.com/25250112/129137024-02943390-9064-4ef5-95c6-b7e72e3ae07b.png)

还有一部分网站像这样的,没有继续访问的选项,且证书也变为自签证书了:
![屏幕截图 2021-08-12 120800](https://user-images.githubusercontent.com/25250112/129137027-b261017d-fd42-4211-8c4e-4f75d56bafb6.png)

一部分国外的视频网站,就像YouTube这样:
![屏幕截图 2021-08-12 120511](https://user-images.githubusercontent.com/25250112/129137030-812a821c-6706-4e75-ab51-56d552854d0c.png)

还望您能解答下,谢谢您不辞辛苦的为我们创造科学上网的环境,谢谢!!!

**Comment by hcym** [comment]
ipv6节点代理可以，也就是wan能正常获取，不用开什么实验功能，至于你说的可能是系统缺什么模块，尤其大雕源码，官方源码没问题，我用官方的必须去掉两个模块，不然lan口也获取ipv6，干扰广告屏蔽

**Comment by Lee917** [comment]
> ipv6节点代理可以，也就是wan能正常获取，不用开什么实验功能，至于你说的可能是系统缺什么模块，尤其大雕源码，官方源码没问题，我用官方的必须去掉两个模块，不然lan口也获取ipv6，干扰广告屏蔽

请问您说的大雕源码是指Lean的源码吗?
还有我的这个问题会不会是 https://github.com/kenzok8/openwrt-packages 封装的问题呢?他这里面的各个插件应该是使用的原开发者的代码吧?请问我需要去那里提issues吗?

**Comment by handsomeji** [comment]
你ipv6是NAT6吗？

**Comment by Lee917** [comment]
> 你ipv6是NAT6吗？

您好，我的IPv6不是NAT6，请问是需要NAT6才能正常使用PassWall的IPv6代理吗？
谢谢您的回复！

**Comment by hcym** [comment]
我的是单臂，有时用移动猫拨号，有时用路由拨号，都正常使用ipv6节点，但是特地少编译的模块，让路由下级设备没有ipv6，主要是为了openclash，你最好自己编译一次，用官方21.02的，默认ipv6兼容性非常好，根本就不需要设置，不需要任何设置，然后再用lean的就明白应该增加什么减少什么

**Comment by xiaorouji** [comment]
Need NAT6.
