### ISSUE TITLE
各位，TCP代理方式改为TPROXY后能正常科学上网不？

### ISSUE THREAD

**Issue by lxhao61** [Openwrt-Passwall/openwrt-passwall#1395]
TCP代理方式有REDIRECT（默认）、TPROXY两种配置选择，见如下：
![image](https://user-images.githubusercontent.com/24571146/129189324-8ae9d4a1-912e-4b03-8eeb-39af7d386743.png)
发现改为TPROXY后就不能正常科学上网了，想知道各位是否与我发现一样。目前我测试确认：两台不同架构CPU的硬路由器都出现这个问题。觉得这个问题不是个案，故此询问一下大家情况（x86软路由器与非x86软路由器各自情况），也好让大佬们重视及解决这个问题。
[此问题是使用Hysteria发现的，Hysteria需要工作在TPROXY下，否则不能启动。](https://github.com/xiaorouji/openwrt-passwall/issues/1379)

**Comment by rivernofish** [comment]
x86软路由，redirect和tproxy均正常，xray，hysteria都试过。
但tproxy模式下跟godproxy有冲突，表现在打开godproxy且ios设备安装godproxy证书后无法科学上网，redirect模式下就没问题。

**Comment by rivernofish** [comment]
对了，UDP不转发端口我加了53，不加就不行

**Comment by lxhao61** [comment]
> x86软路由，redirect和tproxy均正常，xray，hysteria都试过。
> 但tproxy模式下跟godproxy有冲突，表现在打开godproxy且ios设备安装godproxy证书后无法科学上网，redirect模式下就没问题。

谢谢反馈！

**Comment by lxhao61** [comment]
> 对了，UDP不转发端口我加了53，不加就不行

我按照你说的加了53，硬路由器还是无效。

**Comment by yunxi993** [comment]
不能

**Comment by lxhao61** [comment]
> 不能

硬路由器是吧？

**Comment by LitCcc** [comment]
N1做旁路由可以

**Comment by yunxi993** [comment]
> > 不能
> 
> 硬路由器是吧？

软的,ARM

**Comment by lxhao61** [comment]
> > > 不能
> > 
> > 
> > 硬路由器是吧？
> 
> 软的,ARM

ARM架构一般是硬路由器，你这个路由器具体型号是？

**Comment by lxhao61** [comment]
> N1做旁路由可以

此情况下跟TPROXY无关了。

**Comment by handsomeji** [comment]
用REDIRECT也没什么问题，会用ipt2socks转换

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/1342#issuecomment-898533169
有可能与这个有关系

**Comment by malikshi** [comment]
Client devices can't surf, but i can do speedtest from terminal openwrt.

**Comment by lxhao61** [comment]
> 用REDIRECT也没什么问题，会用ipt2socks转换

大佬，用REDIRECT本来就无问题呀，固件也默认编译了ipt2socks的。
![image](https://user-images.githubusercontent.com/24571146/129814867-77efa367-6d18-4b2c-bb56-4aa792bd7309.png)

**Comment by lxhao61** [comment]
> [#1342 (comment)](https://github.com/xiaorouji/openwrt-passwall/issues/1342#issuecomment-898533169)
> 有可能与这个有关系

仔细查看及测试了，问题没有解决，觉得应该与它无关。
从目前反馈来看，非x86软路由器的TPROXY模式都有问题。觉得TPROXY默认配置无法适应硬件差异引起的：软路由器的逻辑接口与网口直接绑定，而非x86软路由器的逻辑接口是通过‘VLAN交换机’与网口绑定。

**Comment by lxhao61** [comment]
> [#1342 (comment)](https://github.com/xiaorouji/openwrt-passwall/issues/1342#issuecomment-898533169)
> 有可能与这个有关系

大佬，不好意思，问题终于找到了：是固件核心版本问题影响，跟passwall无关。
Lienol大19.07版本不能支持TPROXY模式（我之前所用），换Lienol大main版或Lean大源编译，问题解决，推荐Lean大源。

**Comment by handsomeji** [comment]
我用的就是Lienol的19.07

**Comment by lxhao61** [comment]
> 我用的就是Lienol的19.07

你软路由器吧。我硬路由器用Lienol大19.07源无论怎么折腾都不行，换Lienol大main版或Lean大固件源，问题一下子就解决了。

**Comment by handsomeji** [comment]
这和软硬路由无关系

**Comment by lxhao61** [comment]
> 这和软硬路由无关系

应该是Lienol大19.07源有BUG，造成硬路由器无法使用TPROXY模式。
