### ISSUE TITLE
xray trojan节点访问控制里为单独设备指定, 无法连接

### ISSUE THREAD

**Issue by Paris0-0** [Openwrt-Passwall/openwrt-passwall#1400]
如果在全局tcp那里指定xray或者trojan节点可以正常使用, 把全局换成订阅的ssr节点,在访问控制里单独为某个ip的设备指定xray/trojan节点就没法使用, 如果单独指定ssr的节点也能正常用..是为啥

**Comment by handsomeji** [comment]
ssr节点是否能正常使用？

**Comment by Paris0-0** [comment]
我订阅的机场ssr节点在访问控制里给某个设备单独指定可以正常使用, 我自建的节点是一个服务器用xray搭建的xray,和fallback的trojan,ss-wss,在全局指定时可以正常用,但单独指定都不能用..

**Comment by handsomeji** [comment]
试试最新源码
