### ISSUE TITLE
遇到一个不知道是不是BUG的问题，PW好像是会影响pppoe拨号？

### ISSUE THREAD

**Issue by db-one** [Openwrt-Passwall/openwrt-passwall#1404]
Sun Aug 15 08:34:50 2021 daemon.warn pppd[19712]: Timeout waiting for PADS packets
Sun Aug 15 08:34:50 2021 daemon.err pppd[19712]: Unable to complete PPPoE Discovery
Sun Aug 15 08:34:50 2021 daemon.info pppd[19712]: Exit.
Sun Aug 15 08:34:50 2021 daemon.notice netifd: Interface 'wan' is now down
Sun Aug 15 08:34:50 2021 daemon.notice netifd: Interface 'wan' is setting up now
Sun Aug 15 08:34:50 2021 daemon.err insmod: module is already loaded - slhc
Sun Aug 15 08:34:50 2021 daemon.err insmod: module is already loaded - ppp_generic
Sun Aug 15 08:34:50 2021 daemon.err insmod: module is already loaded - pppox
Sun Aug 15 08:34:50 2021 daemon.err insmod: module is already loaded - pppoe
Sun Aug 15 08:34:50 2021 daemon.notice netifd: wan (20776): uci: Entry not found
Sun Aug 15 08:34:50 2021 daemon.notice netifd: wan (20776): sh: out of range
Sun Aug 15 08:34:50 2021 daemon.info pppd[20809]: Plugin rp-pppoe.so loaded.
Sun Aug 15 08:34:50 2021 daemon.info pppd[20809]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
Sun Aug 15 08:34:50 2021 daemon.notice pppd[20809]: pppd 2.4.8 started by root, uid 0
Sun Aug 15 08:35:05 2021 daemon.warn pppd[20809]: Timeout waiting for PADS packets
Sun Aug 15 08:35:05 2021 daemon.err pppd[20809]: Unable to complete PPPoE Discovery
Sun Aug 15 08:35:05 2021 daemon.info pppd[20809]: Exit.
Sun Aug 15 08:35:05 2021 daemon.notice netifd: Interface 'wan' is now down
Sun Aug 15 08:35:05 2021 daemon.notice netifd: Interface 'wan' is setting up now
Sun Aug 15 08:35:05 2021 daemon.err insmod: module is already loaded - slhc
Sun Aug 15 08:35:05 2021 daemon.err insmod: module is already loaded - ppp_generic
Sun Aug 15 08:35:05 2021 daemon.err insmod: module is already loaded - pppox
Sun Aug 15 08:35:05 2021 daemon.err insmod: module is already loaded - pppoe
Sun Aug 15 08:35:05 2021 daemon.notice netifd: wan (21550): uci: Entry not found
Sun Aug 15 08:35:05 2021 daemon.notice netifd: wan (21550): sh: out of range
Sun Aug 15 08:35:05 2021 daemon.info pppd[21622]: Plugin rp-pppoe.so loaded.
Sun Aug 15 08:35:05 2021 daemon.info pppd[21622]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
Sun Aug 15 08:35:05 2021 daemon.notice pppd[21622]: pppd 2.4.8 started by root, uid 0

上面是日志
具体问题是，PW开启状态重启路由重新拨号时候会一直无法拨号成功，看了下日志好像是找不到pppoe接口？
多次都是这个没有发现问题，还以为是拨号问题，就一直等着，大概一分多钟或者几分钟之后也能拨号成功
后来尝试关闭了PW，然后每次重启都可以直接秒拨号成功了

具体也不知道是不是PW影响的，但感觉可能是有关系，麻烦大佬看下，辛苦了

**Comment by hdrafyy** [comment]
你好，请问一下你的OpenWrt-AutoBuild项目如何增加插件？我看到编译清单里面是有的，但是编译好的固件没有那个项目，另外如果想增加清单以外的插件应该如何操作呢？我是外行人，求指点！因为你的项目里没有issues选项，所以找到这里来了。

**Comment by db-one** [comment]
非源码自带的插件，需要先添加源码，再添加编译插件名，如果是大雕自带的，直接添加插件名字就可以

不要在这里打扰大佬们了
