### ISSUE TITLE
hysteria binary not found+ xray shunt doesn't work with hysteria

### ISSUE THREAD

**Issue by malikshi** [Openwrt-Passwall/openwrt-passwall#1405]
please make adjustments for hysteria-no-tun it's work with the no-tun version

**Comment by malikshi** [comment]
Another problem. Hysteria use port 2083 and it's conflict with xray shunt port which is using port 2083?

**Comment by handsomeji** [comment]
Maybe.

**Comment by malikshi** [comment]
Yes it's. Deactivate hysteria and passwall works again. Hemmm quite interesting there.

**Comment by malikshi** [comment]
@xiaorouji i found a way to fix it. 
I have total 3 node
Hysteria
Ss-rust shadowsocks no plugin
Ss-rust shadowsocks obfs.
Start shunt the result obfs doesn't work because port already bind.
So i changes
Ss-rust shadowsocks obfs to ss-libev obfs and works without issues port.
