### ISSUE TITLE
4.32版本，在直连/代理名单管理界面，点击保存&应用，没有任何界面loading显示

### ISSUE THREAD

**Issue by liyuhaolol** [Openwrt-Passwall/openwrt-passwall#1406]
事实上，似乎功能是正常保存了，属于UI的BUG。应该

**Comment by db-one** [comment]
我这边测试似乎正常啊

**Comment by liyuhaolol** [comment]
> 我这边测试似乎正常啊

我这边是8月8日自己编译的版本，我看版本号是4.32，当我点开直连/代理名单管理界面，在那个界面上直接点保存&应用，进度条会开始显示，但是界面不会显示任何的Loading占位图，请问你也这样么？点到其他页卡上，点就会显示loading，只有这个页卡不显示。

**Comment by db-one** [comment]
你用的是1907以上的luci版本吧？我的是1806一切正常

**Comment by liyuhaolol** [comment]
> 你用的是1907以上的luci版本吧？我的是1806一切正常

害，我必然也是1806啊

**Comment by handsomeji** [comment]
不影响
