### ISSUE TITLE
负载均衡未启用

### ISSUE THREAD

**Issue by ZqinKing** [Openwrt-Passwall/openwrt-passwall#1409]
配置了负载均衡，但是一致显示未启用。后台看进行也没有haproxy。1188端口也没有被监听。查看配置文件已经有负载均衡相关的配置生成。大佬，该怎么查这个问题呢？

**Comment by handsomeji** [comment]
恢复配置重新配置一遍试试先

**Comment by ZqinKing** [comment]
> 恢复配置重新配置一遍试试先

负载均衡该使用节点里面还是单独的负载均衡table页的那个呢？这两个有差别吗？

**Comment by ZqinKing** [comment]
> 恢复配置重新配置一遍试试先

重新配置了一遍，需要/var/etc/passwall/bin/haproxy -f /var/etc/passwall/haproxy/confi
g.cfg这样才能开起来。。。
