### ISSUE TITLE
dns不稳定

### ISSUE THREAD

**Issue by haitun001** [Openwrt-Passwall/openwrt-passwall#1412]
经常出现需要daili的网站出现dns错误的情况。怀疑pdnsd在不断重启或者passwall本身在重启。问题出现时只要稍等一下或者刷新一下网页就会好。近期的版本都有这个情况，希望修复一下。谢谢。如果需要我配合提供任何信息都可以。

**Comment by xwcoco** [comment]
以前经常出现这种问题，推荐使用mosdns加上自建的dns-query，还可以加上ecs,本地的直接使用国内的dns服务器，外面的使用自建或不需要代理的dns-query(好像直接访问的只剩下https://1.0.0.1/dns-query）

**Comment by hcym** [comment]
默认的很稳定，总之不能动，用gfw表就用大雕的，表现好一点

**Comment by haitun001** [comment]
目前临时解决了这个问题，第一内核编译要用5.4第二路由器所有和ipv6有关系的都要关掉禁用。就好了。dns不用pdnsd用xray的dns

**Comment by hcym** [comment]
ipv6没有事，多数节点都是6的，不过lan口ipv6是禁止的
