### ISSUE TITLE
使用GFW规则墙内墙外网址都不能访问，但使用中国列表以外则都正常，不知为何？

### ISSUE THREAD

**Issue by petraklux** [Openwrt-Passwall/openwrt-passwall#1413]
使用GFW规则墙内墙外网址都不能访问，但使用中国列表以外则都正常。但passwall运行状态页面的google连接及github连接测试正常。

使用openwrt 21.02，20210807日编译的。启用了adguardhome，并设置重定向53端口到adguardhome

**Comment by handsomeji** [comment]
你agh上游dns填的什么

**Comment by petraklux** [comment]
> 你agh上游dns填的什么

211.137.58.20
211.137.64.163
223.5.5.5

**Comment by handsomeji** [comment]
那肯定是不行的

**Comment by handsomeji** [comment]
`并设置重定向53端口到adguardhome`
agh上游应填127.0.0.1

**Comment by tianiue** [comment]
![Uploading QQ截图20210818174852.png…]()
可以手动指向dns，ChinaDNS-NG勾选了解析不到ipv6，我是群晖ddns，其他不清楚
