### ISSUE TITLE
Apple规则（非bug，need help）

### ISSUE THREAD

**Issue by jh0072110** [Openwrt-Passwall/openwrt-passwall#1427]
可能真的没什么人用Apple TV+的缘故…
现在有个很尴尬的问题…
默认 直连/代理名单管理 中有apple.com，保持默认的情况下绝大多数Apple服务正常，但Apple TV+不太正常（也许是走了直连，一卡一卡的非常不稳定），删除该条目的话，Apple TV+可以正常且高清流畅播放，但很多Apple服务会变得不正常（比方说HomePod会直接显示掉线/查找服务不在线/地图时不时也会无法刷新）…
所以need some help，有没有什么可以两全其美的方案……

**Comment by handsomeji** [comment]
可以抓包看看apple tv的域名

**Comment by jh0072110** [comment]
> 可以抓包看看apple tv的域名

我晚上试试…（不过我不太会可能搞不定ಥ_ಥ）

**Comment by jh0072110** [comment]
> 可以抓包看看apple tv的域名

我果然没看明白=。=
![image](https://user-images.githubusercontent.com/50496854/131983785-4f2b61ba-683f-431b-a4c7-f634b5f344f3.png)
理论上好像是图上的xxx.tv.apple.com？（我瞎JB猜的）

**Comment by handsomeji** [comment]
不清楚 可以试试把 tv.apple.com 加入到代理列表后清空IPSET再试试

**Comment by jh0072110** [comment]
> 不清楚 可以试试把 tv.apple.com 加入到代理列表后清空IPSET再试试

非常有用！十分感谢！暂时感觉十分完美！看起来能加入默认设置了(⁎⁍̴̛ᴗ⁍̴̛⁎)
