### ISSUE TITLE
请教一下日志错误信息问题

### ISSUE THREAD

**Issue by smdx** [Openwrt-Passwall/openwrt-passwall#1429]
各位大佬请教一下错误信息问题，梯子能正常使用打开翻墙网站都正常就是会有错误日志请教一下怎么回事，谢谢。

OpenWrt x86_64 LuCI Master (git-21.238.35254-83494a9) 内核版本	5.10.61
passwall  4.34

![pass](https://user-images.githubusercontent.com/9279217/132037351-ced1a283-8fbb-423d-8aae-323666d3d59c.jpg)

**Comment by handsomeji** [comment]
断流

**Comment by smdx** [comment]
> 断流

原来如此，用的xray分流。不知道是不是smartdns新版的原因上个版本都没这个问题的。谢谢了
