### ISSUE TITLE
反馈个问题，直连/代理名单管理无效

### ISSUE THREAD

**Issue by smdx** [Openwrt-Passwall/openwrt-passwall#1430]
反馈个问题，在 直连/代理名单管理 中代理名单已经添加了相关域名例如：gstatic.com后无法生效。
该域名还是直连导致youtube、gmail、google硬盘等网站一直载入。

OpenWrt x86_64 LuCI Master (git-21.238.35254-83494a9) 内核版本 5.10.61
passwall 4.34

![2021-09-04_092339](https://user-images.githubusercontent.com/9279217/132077912-d03f4016-c259-4d79-8809-80d69a330933.jpg)

**Comment by handsomeji** [comment]
日志？

**Comment by handsomeji** [comment]
如果你用的是v2ray/xray分流：
添加一个分流规则，填入`gstatic.com`，并且要保证China规则在最后。
或者China规则不开启，选择关闭，透明代理模式选择`中国列表外`

**Comment by smdx** [comment]
> 日志？

![2021-09-04_172018](https://user-images.githubusercontent.com/9279217/132089646-40e0bcc9-19a5-4a53-a8d6-15186b6aa899.jpg)

![2021-09-04_172145](https://user-images.githubusercontent.com/9279217/132089661-46151fd0-4377-41a7-bde7-a2c874ade3a7.jpg)

**Comment by smdx** [comment]
> 如果你用的是v2ray/xray分流：
> 添加一个分流规则，填入`gstatic.com`，并且要保证China规则在最后。
> 或者China规则不开启，选择关闭，透明代理模式选择`中国列表外`

的确是用的xray分流，明白了我设置看看。谢谢了
