### ISSUE TITLE
使用xray分流容易断网

### ISSUE THREAD

**Issue by xc66** [Openwrt-Passwall/openwrt-passwall#1431]
使用xray分流容易断网，不使用的话就很稳定

**Comment by keyboydg** [comment]
我的是XRAY分流直接不会启动，已经好几个版本了，也是这个情况，不知道什么原因呢。

**Comment by smdx** [comment]
> 我的是XRAY分流直接不会启动，已经好几个版本了，也是这个情况，不知道什么原因呢。

出问题都不看日志的么....分流启动不了是因为没有geoip、geosite文件，先选个服务器更新好再换回分流就行了。

**Comment by xc66** [comment]
> > 我的是XRAY分流直接不会启动，已经好几个版本了，也是这个情况，不知道什么原因呢。
> 
> 出问题都不看日志的么....分流启动不了是因为没有geoip、geosite文件，先选个服务器更新好再换回分流就行了。

这两个文件更新后在分流，然后老是断网，是什么问题呢，不分流就不会断？

**Comment by smdx** [comment]
> > > 我的是XRAY分流直接不会启动，已经好几个版本了，也是这个情况，不知道什么原因呢。
> > 
> > 
> > 出问题都不看日志的么....分流启动不了是因为没有geoip、geosite文件，先选个服务器更新好再换回分流就行了。
> 
> 这两个文件更新后在分流，然后老是断网，是什么问题呢，不分流就不会断？

我也是很多断流的日志，但是我打开网页、视频都不影响就不管他了。

**Comment by smdx** [comment]
@xiaorouji
xray分流把默认代理模式设置成gfw就不会出现断流的日志，设置成中国列表以外就会。

**Comment by skylanderno1** [comment]
反复尝试后发现如果规则中包含geo规则就会出现断流的问题，比如geoip:cn、geosite:cn这种，不过目前只测试了xray，还没测试v2ray。

**Comment by handsomeji** [comment]
换用旧的geoip规则

**Comment by yaott2020-666** [comment]
用xray分流，不应该设置全局吗

**Comment by 1klakla1** [comment]
> > 我的是XRAY分流直接不会启动，已经好几个版本了，也是这个情况，不知道什么原因呢。
> 
> 出问题都不看日志的么....分流启动不了是因为没有geoip、geosite文件，先选个服务器更新好再换回分流就行了。

大佬。日志怎么看？我有个问题也想看下日志找找原因
