### ISSUE TITLE
大佬  宽带分配了ipv6 k3使用passwall后 ipv6无法代理

### ISSUE THREAD

**Issue by liaoweiliao521** [Openwrt-Passwall/openwrt-passwall#1437]
大佬  我的是k3刷的是lean大的openwrt  passwall节点使用naiveproxy和hysteria dns使用的是v2raydoh  REDIRECT和TPROXY都分别试过 ipv6都无法代理  ipv4一直都正常代理   testipv6测试显示的ipv6地址也是国内地址 大佬是不是我哪里设置的有问题

**Comment by handsomeji** [comment]
1. 据我所知，passwall的ipv6透明代理只有xray或v2ray能用，其他不行。
2. ipv6必须是NAT类型
3. 我没有带有ipv6的VPS，无法测试

**Comment by a904055262** [comment]
我开了passwall，Ipv6test无法通过

**Comment by liaoweiliao521** [comment]
> 1. 据我所知，passwall的ipv6透明代理只有xray或v2ray能用，其他不行。
> 2. ipv6必须是NAT类型
> 3. 我没有带有ipv6的VPS，无法测试

恩  谢谢大佬的回复  我试了naiveproxy hysteria  Trojan 都是无法代理ipv6  而且使用手机热点代理后同样无法代理ipv6  应该是ipv6自身的问题  再次感谢大佬  另外我现在用的是带有ipv6的vps 您要是需要测试的话 我这台您先测试

**Comment by liaoweiliao521** [comment]
> 我开了passwall，Ipv6test无法通过

**Comment by pengkaiwei** [comment]
我开了 IPv6透明代理后，所有的黑名单网站，都不开了，也包括外面的ipv6

TCP代理方式 TPROXY
IPv6透明代理(TProxy)  
实验特性，请确保你的节点支持IPv6

**Comment by peaceanddemocracy** [comment]
同样问题，passwall对ipv6的支持有问题

**Comment by hcym** [comment]
ipv6的节点肯定没问题，什么歇斯底里也正常
哪个透明开关我都不碰的，你们说的是不是lan口，这个东西我是没有用过，最近ipv4挂了很多，全是靠6的

**Comment by peaceanddemocracy** [comment]
> ipv6的节点肯定没问题，什么歇斯底里也正常 哪个透明开关我都不碰的，你们说的是不是lan口，这个东西我是没有用过，最近ipv4挂了很多，全是靠6的

感谢大佬，我试了下正常了，可能之前本地路由的ipv6有问题
