### ISSUE TITLE
xray 1.3.0版本开始已经支持Fullcone UDP，但是使用Passwall NAT无效。

### ISSUE THREAD

**Issue by 1klakla1** [Openwrt-Passwall/openwrt-passwall#1438]
如题。
![1](https://user-images.githubusercontent.com/49523592/132171495-7bdc96e7-aeca-43ea-8c65-1507ade7170d.png)

**Comment by handsomeji** [comment]
看到docker就知道什么回事了

**Comment by 1klakla1** [comment]
> 看到docker就知道什么回事了

啥意思啊大佬。
我现在基本肯定是Passwall引起的问题了，同一个节点。换个客户端就不会Udp Block

**Comment by 1klakla1** [comment]
> 看到docker就知道什么回事了

大佬。刚测试过了，SSR+就没问题。。。应该是Passwall的BUG

**Comment by handsomeji** [comment]
都说了 9成就是docker的原因

**Comment by handsomeji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/1320

**Comment by 1klakla1** [comment]
> 都说了 9成就是docker的原因

谢谢大佬，我先好好研究一下。
再次表示感谢！

**Comment by 1klakla1** [comment]
> #1320

大佬，问题解决了！
非常感谢！下个版本可以修复这个问题嘛？

**Comment by handsomeji** [comment]
docker导致的问题 为什么要passwall修复？

**Comment by handsomeji** [comment]
不建议openwrt用docker（无论你是否开启，这都会导致TPROXY失效）

**Comment by 1klakla1** [comment]
> docker导致的问题 为什么要passwall修复？

懂了大佬，以后第一件事先把Docker完全卸载！路由器这种东西根本用不到这个。。。。调试的话PVE里面做个快照多简单，哈哈
