### ISSUE TITLE
代理列表不起作用

### ISSUE THREAD

**Issue by sy19890515** [Openwrt-Passwall/openwrt-passwall#1442]
经常碰到这种情况：
网站A的域名已经放在代理列表中，passwall开pac模式连接a节点，能上google，打不开网站A，开全局模式可以打开网站网站A
关闭passwall，在电脑上打开客户端，同样连接a节点，把A的域名放到用户pac列表中，开pac模式和全局模式都可以打开网站A

但passwall却又不是永远无视代理列表，经常“今天代理列表不起作用，折腾半天折腾不好，睡觉，第二天回家继续看的时候发现开pac模式又能打开网站A了”，可是过一段时间又出现pac模式打不开网站A的问题

请问是怎么回事啊？

**Comment by sy19890515** [comment]
比如今天刚回家时，我可以打开google.ca（不是google.com）和steamcommunity.com，过了一会我更新了一下订阅列表，然后就打不开google.ca和steamcommunity.com了，但能打开google.com。可是过了大概半小时，我能打开google.ca了，依然打不开steamcommunity.com，然后我发了这个issue。

结果发完以后，我又去试着打开steamcommunity.com，还是打不开，但是又过了5分钟不到，居然就打开了，而这期间我一直没改变过passwall设置，就是反复开关而已

**Comment by handsomeji** [comment]
清空DNS缓存

**Comment by sy19890515** [comment]
在哪里清空？

Sincerely,

Yi Shi


________________________________

**Comment by sy19890515** [comment]
> 清空DNS缓存

远程DNS换成208.67.222.222就好了，8.8.8.8和8.8.4.4都有我说的问题
