### ISSUE TITLE
反馈一个BUG,官方2021.08.21版本Passwall，Xray分流无效。

### ISSUE THREAD

**Issue by 1klakla1** [Openwrt-Passwall/openwrt-passwall#1444]
![1](https://user-images.githubusercontent.com/49523592/132930906-0c058dc8-d9eb-4607-995e-a58a920b5ed1.jpg)
![2](https://user-images.githubusercontent.com/49523592/132930910-1194ae26-6b24-48e2-addf-f3fe582327c7.jpg)
![3](https://user-images.githubusercontent.com/49523592/132930911-11d0a6be-da09-47f0-8105-1f9ff0738ef6.jpg)

规则已更新，DNS模式尝试过每一种模式，均不生效。
具体症状表现为访问外网不通，ping外网域名不通。
改成单独节点模式恢复正常。

**Comment by 1klakla1** [comment]
补充：
猜测应该是这个版本的问题，在eSir编译的高大全V9.1固件中没有此问题。

**Comment by lededev** [comment]
你可以将这两个版本的luci-app-passwall的文件比较一下差异，看看是什么改动造成的。

**Comment by handsomeji** [comment]
使用旧版本的没有义务解决

**Comment by dl250** [comment]
新版本，节点老是连不上，节点检测哪里显示节点都是正常，谷歌连通那里也是pin不通，我在手机上测这节点正常可以谷歌等网站的，但最新pass是连不上的
