### ISSUE TITLE
希望两项优化可以实现

### ISSUE THREAD

**Issue by lxhao61** [Openwrt-Passwall/openwrt-passwall#1445]
1、希望解决TCP代理方式（redirect或tproxy）自动切换问题
目前情况：naiveproxy只能工作在redirect下，hysteria只能工作在tproxy下。当naiveproxy与hysteria切换时，还需要TCP代理方式切换，有点麻烦。希望naiveproxy与hysteria切换时，TCP代理方式（redirect或tproxy）自动切换。或者改进naiveproxy也可以工作在tproxy下，TCP代理方式切换到tproxy就可以通用了。
![image](https://user-images.githubusercontent.com/24571146/132932377-52c34ce1-f056-4d26-9f31-1f01f483d3fd.png)

2、希望配置界面加入Xray-plugin选项
目前情况：编译luci中无Xray-plugin选项，配置界面也无Xray-plugin选项（即使编译了此插件）。
![image](https://user-images.githubusercontent.com/24571146/132932425-2b0733d3-5021-4a0e-a1b6-455c721a6d3e.png)

希望大佬能优化上述，谢谢！

**Comment by xiaorouji** [comment]
之前不是说过 一直都可以的吗

**Comment by handsomeji** [comment]
用不了请自己排除问题了

**Comment by handsomeji** [comment]
类型不支持TPROXY或REDIRECT时 会调用ipt2socks，请检查下进程看看

**Comment by lxhao61** [comment]
> 类型不支持TPROXY或REDIRECT时 会调用ipt2socks，请检查下进程看看

大佬，我说TCP代理方式（redirect或tproxy）跟随naiveproxy或hysteria节点切换时自动切换。不对应时，不需再次切换到redirect或tproxy。

**Comment by handsomeji** [comment]
没有必要
