### ISSUE TITLE
最新版本Passwall，Xray分流前置代理有BUG，无论怎么选前置代理，都是不生效的，访问不了外网。

### ISSUE THREAD

**Issue by 1klakla1** [Openwrt-Passwall/openwrt-passwall#1447]
单独测试每一个节点，都是正常的。
![1](https://user-images.githubusercontent.com/49523592/132980105-f7518222-b9e8-4674-8fd5-b6af4d7500a5.jpg)
![2](https://user-images.githubusercontent.com/49523592/132980108-cbc7af5c-4986-4507-9464-2ef4196fab80.jpg)
![3](https://user-images.githubusercontent.com/49523592/132980128-5f531880-19dd-409b-b6f0-63eec7a9da79.jpg)

**Comment by Hiyajomaho-num9** [comment]
上传日志
```
Xray 1.4.3 (Xray, Penetrates Everything.) OpenWrt (go1.17 linux/arm)
A unified platform for anti-censorship.
2021/09/13 04:08:00 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
Failed to start: main: failed to load config files: [/var/etc/passwall/TCP.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ads > infra/conf: failed to load geosite: CATEGORY-ADS > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /usr/share/xray/geosite.dat: no such file or directory
```
经确认确实缺少了相应的geosite.dat和geoip.dat
目前解决方案为新创路径/usr/share/xray/，后放入geosite.dat和geoip.dat即可正常工作
[Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)

**Comment by Aukansh** [comment]
![QQ图片20210914004333](https://user-images.githubusercontent.com/53339509/133123860-45d62b40-7494-4986-a8db-09c2890fb74f.png)
更新错误！！

**Comment by Hiyajomaho-num9** [comment]
> ![QQ图片20210914004333](https://user-images.githubusercontent.com/53339509/133123860-45d62b40-7494-4986-a8db-09c2890fb74f.png)
> 更新错误！！

你这应该发new issue才对

**Comment by 1klakla1** [comment]
> 上传日志
> 
> ```
> Xray 1.4.3 (Xray, Penetrates Everything.) OpenWrt (go1.17 linux/arm)
> A unified platform for anti-censorship.
> 2021/09/13 04:08:00 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
> Failed to start: main: failed to load config files: [/var/etc/passwall/TCP.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:category-ads > infra/conf: failed to load geosite: CATEGORY-ADS > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /usr/share/xray/geosite.dat: no such file or directory
> ```
> 
> 经确认确实缺少了相应的geosite.dat和geoip.dat
> 目前解决方案为新创路径/usr/share/xray/，后放入geosite.dat和geoip.dat即可正常工作
> [Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)

感谢回复！
