### ISSUE TITLE
haproxy console can't open

### ISSUE THREAD

**Issue by kokenot** [Openwrt-Passwall/openwrt-passwall#1496]
Tue Oct 12 16:54:00 2021 daemon.info procd: Instance haproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

got this error log. i'm using 
OpenWrt R21.10.1 / LuCI Master (git-21.280.14233-9b796b1) 
5.14.11-flippy-66+
AMedia X96 Max+

after setting and enable LB, i try to access the console 192.168.1.1:1188 but it just show site cannot be reach

**Comment by kokenot** [comment]
haproxy button only appear if i activate 1 node. if selecting 2 nodes the button disappear and i can't access the console. using ip to access still can't

**Comment by handsomeji** [comment]
what the passwall version?
