### ISSUE TITLE
分流问题

### ISSUE THREAD

**Issue by Sunnice** [Openwrt-Passwall/openwrt-passwall#1498]
分流内China选择直连的话，tcp就无法启动，选择关闭才能启动tcp

**Comment by handsomeji** [comment]
请查看TCP日志，我估计是因为没有geoip和geosite

**Comment by Sunnice** [comment]
> 请查看TCP日志，我估计是因为没有geoip和geosite

Xray 1.4.5 (Xray, Penetrates Everything.) OpenWrt (go1.17.1 linux/arm)
A unified platform for anti-censorship.
2021/10/15 00:46:25 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
Failed to start: main: failed to load config files: [/var/etc/passwall/TCP.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: cn > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /usr/share/xray/geoip.dat: no such file or directory
的确是这样的，请问大佬怎么解决

**Comment by handsomeji** [comment]
更新规则
