### ISSUE TITLE
国外只查询ipv4

### ISSUE THREAD

**Issue by hplee0120** [Openwrt-Passwall/openwrt-passwall#1508]
queryStrategy: 可用配置为 "UseIP" | "UseIPv4" | "UseIPv6", 其中UseIPv4 只查询 A 记录, UseIPv6只查询 AAAA 记录. 默认值为 UseIP, 即查询两者.

xray1.5.0以上更新 是否能考虑增加一个国外dns只查询ipv4的功能开关。实现国内双栈，国外过滤ipv6

**Comment by badgv** [comment]
自带的pdnsd已经有这个功能了
![image](https://user-images.githubusercontent.com/45598380/138280128-965e383f-b49c-436e-bbc2-a5aac025f340.png)
![image](https://user-images.githubusercontent.com/45598380/138280323-4cb0f90b-b033-47b6-8888-c87945d8703e.png)
