### ISSUE TITLE
编译后发现`节点订阅`里面怎么少了3个选项按钮？

### ISSUE THREAD

**Issue by se7enmuting** [Openwrt-Passwall/openwrt-passwall#1510]
#### 看下面2张图：
- **图1**如下：缺少3个选项按钮
![屏幕截图 2021-10-21 205918](https://user-images.githubusercontent.com/889925/138289001-f2ea89ef-7840-49c6-a119-09a46e4a21f6.jpg)
- **图2**如下：
![屏幕截图 2021-10-21 212514](https://user-images.githubusercontent.com/889925/138289065-9c981d11-b17e-4c5e-a96b-65f0cd31929a.jpg)
**图1** 我是用[lean-master](https://github.com/coolsnowwolf/lede)编译的，分别在10月13号和10月21号编译的，都缺3个选项按钮。用`echo 'src-git lienol https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default`的方式。
我又看了下我10月6号和9号，都有把lean版本reset到这个[commit](https://github.com/coolsnowwolf/lede/tree/687407acdc585355acd24726eac61dca60cd06fb)各编译过一次，都有这3个按钮的。
**图2** 我是用[immortalwrt-18.06-k5.4](https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06-k5.4)编译的,10月18号编译的。用的他们自维护的[immortalwrt/luci/luci-app-passwall](https://github.com/immortalwrt/luci/tree/openwrt-18.06-k5.4/applications/luci-app-passwall)，有这3个按钮。
这个是 passwall 的问题还是lean的luci的问题？

**Comment by greennyreborn** [comment]
应该是改UI了，订阅改为在下面链接处每个单独点

**Comment by se7enmuting** [comment]
> 应该是改UI了，订阅改为在下面链接处每个单独点

哦，再仔细看了下，`开启自动更新订阅`和`允许不安全连接`放到下面每个单独的订阅里面了，每个点多了单独的手动订阅更新。

**但是：像我这种有5,6个订阅的，有时想一下全部手动订阅一下，现在只能每个都要单独点一次，每次还要等他刷完才能点下一个，好慢吗。。。**
**能不能把 `手动订阅`（全部手动更新订阅） 这个按钮恢复啊？**
想一下，你既然保留了 `删除所有点阅节点`，当我点了这个之后，再要重新手动更新下所有订阅，那一个个点不是很费事了。。。
