### ISSUE TITLE
开启passwall后跟NAT有冲突

### ISSUE THREAD

**Issue by xiaobaishu1** [Openwrt-Passwall/openwrt-passwall#1512]
开启后NAT从第一种类型变成的第三种

这是没开启前的
![QQ图片20211022111746](https://user-images.githubusercontent.com/53339509/138388069-267688bb-4d75-4a18-be5c-17146c91739b.png)
  这是开启后的 未能正常显示 重启后可见
![QQ图片20211022112053](https://user-images.githubusercontent.com/53339509/138388178-e8f11c7d-5104-4c09-bb46-39d9f2ab3020.png)

**Comment by handsomeji** [comment]
你节点不支持UDP吧
