### ISSUE TITLE
Xray/V2fly分流，1.1.1.1类型IP规则不生效

### ISSUE THREAD

**Issue by SimonTLS** [Openwrt-Passwall/openwrt-passwall#1514]
感谢开发者的付出，能抽空看下Issues辛苦了
树莓派4B+USB网卡作软路由，OpenWrt版本为SuLingGG/OpenWrt-Rpi的Lean版10.22编译
DNS模式为“不过滤”，AdguardHome作为dnsmasq的上游DNS（DNS默认设置也与下述一致）

在规则管理的Xray/V2fly规则中添加后，TCP节点选Xray分流总节点，/var/etc/passwall/TCP.json正确生成如图
![Inked屏幕截图 2021-10-22 203518](https://user-images.githubusercontent.com/58877008/138455153-03d20c9f-160a-443b-9503-630d378da8ee.jpg)

以域名访问该IP对应网站，Log中仍显示该IP走Default路由，tcping该IP则显示走Direct。而geoip:cn中的IP经过tcping测试生效，同1.5.0版本Xray的V2rayN浏览器访问生效。
（网站为VLESS伪装网站，希望直连不经过软路由的代理转发）

![Inked屏幕截图 2021-10-22 203628](https://user-images.githubusercontent.com/58877008/138455552-a77f250a-743c-438a-9ab9-51f632933811.jpg)

**Comment by handsomeji** [comment]
域名解析策略用的什么？

**Comment by SimonTLS** [comment]
默认的IPIfNonMatch，遗漏一点：tcping该IP显示Direct

![Inked屏幕截图 2021-10-22 210216](https://user-images.githubusercontent.com/58877008/138458551-fac7650a-3973-4518-a431-bb3edf885ef0.jpg)

**Comment by handsomeji** [comment]
试试用 IPOnDemand

**Comment by SimonTLS** [comment]
感谢，通过修改etc/config/passwall生成IPOnDemand的json后，访问网站Log中显示Direct。

**Comment by handsomeji** [comment]
luci界面不是可以直接改吗？

**Comment by SimonTLS** [comment]
啊 可能我没找到。或者这个编译好的固件里，自带的PassWall没有？github.com/SuLingGG/OpenWrt-Rpi

**Comment by handsomeji** [comment]
分流节点的节点配置里面

**Comment by SimonTLS** [comment]
谢谢找到了，不好意思🤣
