### ISSUE TITLE
[求助] 訂閱更新後節點重複問題

### ISSUE THREAD

**Issue by TomFoxLee** [Openwrt-Passwall/openwrt-passwall#1520]
各位用 passwall 的大佬們，不知你們有沒有遇到每次節點訂閱更新後，節點重複的問題。

我遇到有一陣子了，之前以為 passwall 後續更新就會好，結果幾個版本之後還是一樣。印象中大概 4.22 左右的時候還正常，後來不記得哪一版就開始這樣。

大體情況如下：每次訂閱更新後（無論自動或手動），之前正常的情況是把原來的節點列表更新，例如新的節點加上，消失的節點就刪掉了。可是前陣子開始，突然變成每次更新後，節點疊加。。。譬如訂閱地址有節點 15 個的話，更新第一次 15 個，更新第二次就變成原有的 15 個之外，又重複了一次 15 個，變成總共 30 個（每個節點出現兩次），然後第三次變 45 個（每個節點出現三次）。。。依此類推。。。不知道有沒有人遇到過？有沒有解決的方法？或者是設定哪裡需要注意的？😓😓

**Comment by TomFoxLee** [comment]
補充一下，同樣的訂閱地址，我用電腦的 v2rayN 更新訂閱的時候不會發生重複的情況，所以推測大概率不是訂閱地址下載節點內容的問題。。。

**Comment by WYC-2020** [comment]
没遇到

**Comment by handsomeji** [comment]
保存配置升级的？

**Comment by TomFoxLee** [comment]
感謝大大回答。我試過以下幾種情況，都出現更新訂閱後節點重複的問題（4.3x 版）：

1. 保存配置下升級 passwall。
2. 用 passwall reset_config 清空 passwall 設置後，重新手動輸入一遍更新設置。
3. 整個 openwrt 重刷，從零開始輸入所有配置，包括但不限於 passwall 部分。

以上三種情況，都會出現節點重複的結果。

我再提供一些細節，希望能對除錯有幫助。

1. 我用的固件是 SuLingGG 的 openwrt-mini，設備是 r2s。
2. 我根據手邊目前還留有的幾個安裝版本來看，passwall 4.22 和 4.26 更新節點都還正常，但似乎是 4.3x 開始出現節點會重複的問題？好像組件更新的部分，在 4.2x 只有提供 xray，4.3x 開始 xray 和 v2ray 都提供，不知道跟這個是不是有關係。。。不過 ss 的節點也一樣會重複。。。所以依然不確定是什麼造成的。。。

目前暫時停留在 4.26 版。希望 xiaorouji 大大有機會時能抽空看一下是什麼原因。同訂閱地址下，拿 v2rayN 和 SSRP 測試更新r節點都不會重複，所以估計地址出問題的機會應該較小。

這裡先感謝大大了！
