### ISSUE TITLE
4.41 DNS 模式 设置 TCP 不通

### ISSUE THREAD

**Issue by Myoko** [Openwrt-Passwall/openwrt-passwall#1526]
4.41  DNS 模式 xray过滤 如下设置 不通！换成 DOH 就没问题 换回 TCP就不通 另外测试了 v2ray 的没有这个问题 只有xray才有

![1](https://user-images.githubusercontent.com/3013386/138987645-406cc757-f2af-44ad-a7bd-a999ba2c9352.jpg)

**Comment by handsomeji** [comment]
xray版本要1.5以上

**Comment by Myoko** [comment]
1.5 好像有问题 目前还在1.45 感谢@xiaorouji 回复
