### ISSUE TITLE
v2ray-core更新v5后，golang1.17编译不过

### ISSUE THREAD

**Issue by bwb0101** [Openwrt-Passwall/openwrt-passwall#1873]
## 描述bug(必填)

更新后的v5版本patches后对golang的需求直接变成了1.18，golang1.17已经无法进行编译，会报错

## 日志信息(必填！)

make[3]: Entering directory '/workdir/openwrt/feeds/passwall/v2ray-core'
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.built
touch /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/workdir/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/workdir/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/v2fly/v2ray-core/v5" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/v2fly/v2ray-core/v5/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3" GO_BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.go_work/build" GO_BUILD_BIN_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/workdir/openwrt/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOARM="" GOMIPS="" GOMIPS64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3=v2ray-core-5.0.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3=v2ray-core-5.0.3 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.go_work/build" GOCACHE="/workdir/openwrt/tmp/go-build" GOMODCACHE="/workdir/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /workdir/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1648924179' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags " -X github.com/v2fly/v2ray-core/v5.build=OpenWrt -X github.com/v2fly/v2ray-core/v5.version=5.0.3 -buildid '1648924179' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

Building targets
github.com/marten-seemann/qtls-go1-18
# github.com/marten-seemann/qtls-go1-18
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:141:43: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:399:45: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:404:46: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/cipher_suites.go:412:45: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/common.go:1496:41: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:177:10: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:183:13: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:211:62: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:973:14: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:1056:33: undefined: any
../../../../../dl/go-mod-cache/github.com/marten-seemann/qtls-go1-18@v0.1.1/conn.go:973:14: too many errors
note: module requires Go 1.18

make[3]: *** [Makefile:111: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.0.3/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/passwall/v2ray-core'
time: package/feeds/passwall/v2ray-core/compile#2.80#0.72#2.40
    ERROR: package/feeds/passwall/v2ray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/v2ray-core/compile] Error 1

## 系统相关信息(必填)

[453e170](https://github.com/xiaorouji/openwrt-passwall/commit/453e170ac79511238e97285c671850f8d2ee2d1a)

## 其他相关信息

[Lienol](https://github.com/Lienol) 22.03版本

**Comment by Beginner-Go** [comment]
等会看看

**Comment by bwb0101** [comment]
看了下patches，主要是sniff.go用1.18的代替了1.17，所以后续的编译都是基于go1.18版本

**Comment by WYC-2020** [comment]
回滚那个patch，下个v2 版本就是1.18了，没必要那么快尝鲜，这个patch打的不完整

**Comment by bwb0101** [comment]
v2ray-core这问题并没有更新

**Comment by bwb0101** [comment]
还是不在支持go1.17了？

**Comment by Beginner-Go** [comment]
是的 升级go1.18就好了

**Comment by WYC-2020** [comment]
> 还是不在支持go1.17了？

我1.77没有任何问题可以编译啊

**Comment by WYC-2020** [comment]
> 还是不在支持go1.17了？

他这个补丁应该是有要求的，要求op的go也要升级到1.18但是l大的并没升级，所以导致用l大的编译就会出现这个问题，你可以回退或者升级go应该就可以解决，只是不知道其他有用到go会不会有问题

**Comment by bwb0101** [comment]
用过l大的master版本，syncthing编译会出问题，官方对其并没有升级，这版本引用的库在go1.18下直接报错，这问题提过，l大让用其他版本

**Comment by bwb0101** [comment]
目前做法我是直接删除了core下的patches目录

**Comment by WYC-2020** [comment]
> 用过l大的master版本，syncthing编译会出问题，官方对其并没有升级，这版本引用的库在go1.18下直接报错，这问题提过，l大让用其他版本

官方的升级了的https://github.com/openwrt/packages/commit/478666b00b8caeccf1d51c44ebb71788b0ca4388
l大的没升级而已，不想升级撤销那个patch即可，我就是撤回的

**Comment by WYC-2020** [comment]
> 用过l大的master版本，syncthing编译会出问题，官方对其并没有升级，这版本引用的库在go1.18下直接报错，这问题提过，l大让用其他版本

我主要是怕升级后其他用到go出问题，就没这样搞

**Comment by bwb0101** [comment]
是的，目前go1.18推出时间比较短，一些插件还没来跟上

**Comment by bwb0101** [comment]
> > 用过l大的master版本，syncthing编译会出问题，官方对其并没有升级，这版本引用的库在go1.18下直接报错，这问题提过，l大让用其他版本
> 
> 官方的升级了的[openwrt/packages@478666b](https://github.com/openwrt/packages/commit/478666b00b8caeccf1d51c44ebb71788b0ca4388) l大的没升级而已，不想升级撤销那个patch即可，我就是撤回的

官方主版本升级的是go，对应的util下的syncthing还是1.82版本，1.8x版本不支持go1.18，官方没有对其升级

**Comment by WYC-2020** [comment]
> > > 用过l大的master版本，syncthing编译会出问题，官方对其并没有升级，这版本引用的库在go1.18下直接报错，这问题提过，l大让用其他版本
> > 
> > 
> > 官方的升级了的[openwrt/packages@478666b](https://github.com/openwrt/packages/commit/478666b00b8caeccf1d51c44ebb71788b0ca4388) l大的没升级而已，不想升级撤销那个patch即可，我就是撤回的
> 
> 官方主版本升级的是go，对应的util下的syncthing还是1.82版本，1.8x版本不支持go1.18，官方没有对其升级

这样啊，其他没看，应该用到go都需要修改吧，等他们修改吧，不折腾哈哈

**Comment by WYC-2020** [comment]
https://github.com/WYC-2020/openwrt-passwall/commit/b04f610298ab51c49fe01f024f89d507d52d7cda
用我这个patch 通杀，如果后续v2 有更新，就可以去掉这个patch
@jkingben @Beginner-Go @MoetaYuko @smallprogram

**Comment by WYC-2020** [comment]
兼容 1.17 1.18

**Comment by bwb0101** [comment]
等会编个固件试试，谢谢大神们
