### ISSUE TITLE
[Bug]: 最新版的passwall中规则列表-代理列表自己添加的规则无效

### ISSUE THREAD

**Issue by wazzx** [Openwrt-Passwall/openwrt-passwall#2449]
### 描述您遇到的bug

如图：最新版添加下自定义规则没有生效
```
good.news
caus.com
oraclecloud.com
google-edit.com
xda-developers.com

#Podcasts
bag.itunes.apple.com
amp-api.podcast.apple.com
bookeeper.itunes.apple.com
buzzsprout.com
```
![Screenshot 2023-04-02 11 32 39](https://user-images.githubusercontent.com/60512548/229329870-7c1595e2-f25a-4091-af8e-da3d7af8f15e.png)

### 复现此Bug的步骤

rt

### 您想要实现的目的

rt

### 日志信息

rt

### 系统相关信息

rt

**Comment by handsomeji** [comment]
保存应用后看日志是否有重启，有就有效
