### ISSUE TITLE
[Feature Request]: 建议默认使用udp与2024.03.07及之后的chinadns-ng通讯

### ISSUE THREAD

**Issue by BGzEroll** [Openwrt-Passwall/openwrt-passwall#3048]
### 描述你想要的新功能

dnsmasq与chinadns-ng之间使用udp个人认为会更加简单高效，也不会整得进程表里一堆dnsmasq进程

### 描述你想要的解决方案

默认使用udp与2024.03.07及之后的chinadns-ng通讯

### 其他信息

详细请看[Discussions](https://github.com/xiaorouji/openwrt-passwall/discussions/3044)

**Comment by SakuraFallingMad** [comment]
可能需要解决的是dnsmasq本身的问题 chinadns-ng 新版倒是解决了解析结果msgsize超过512用tcp的问题。确实发现dnsmasq进程有复数个。

**Comment by BGzEroll** [comment]
> 可能需要解决的是dnsmasq本身的问题 chinadns-ng 新版倒是解决了解析结果msgsize超过512用tcp的问题。确实发现dnsmasq进程有复数个。

dnsmasq那边应该也算是特性吧，新版chinadnsng目前貌似也并没有给出指定监听tcp/udp协议的参数，难顶😂

另外能细说下**解决了解析结果msgsize超过512用tcp的问题**吗，说实话我没看懂这个（

**Comment by SakuraFallingMad** [comment]
> > 可能需要解决的是dnsmasq本身的问题 chinadns-ng 新版倒是解决了解析结果msgsize超过512用tcp的问题。确实发现dnsmasq进程有复数个。
> 
> dnsmasq那边应该也算是特性吧，新版chinadnsng目前貌似也并没有给出指定监听tcp/udp协议的参数，难顶😂
> 
> 另外能细说下**解决了解析结果msgsize超过512用tcp的问题**吗，说实话我没看懂这个（

参考https://github.com/xiaorouji/openwrt-passwall/issues/2960

**Comment by handsomeji** [comment]
請向DNS項目反饋。
