### ISSUE TITLE
[Bug]: proxy_host大小达到94KB会让gfw模式失效

### ISSUE THREAD

**Issue by najloa** [Openwrt-Passwall/openwrt-passwall#3127]
### 描述您遇到的bug

如题，往代理列表中添加任意域名使proxy_host文件的大小达到94KB将会导致gfw模式失效，94KB并不是一个精确值，而是我自用的代理域名列表和快速复现问题的大小

### 复现此Bug的步骤

添加任意域名至代理列表使proxy_host文件的大小达到94KB后重启路由器

### 您想要实现的目的

找到导致问题的原因或修复此bug

### 日志信息

![2](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/995712ed-7125-44d1-876f-eaa5338ce672)

### 截图

![3](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/e7923643-0083-45b8-b645-9212d3b95c83)
![1](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/4cca8b28-5fbb-44f1-94b2-01ab35e3b3be)

### 系统相关信息

Passwall 版本【 4.76-5-smartdns-dev 】
ChinaDNS-NG 版本【 2024.04.13 】
Sing-Box 版本【 1.8.11 】

**Comment by SakuraFallingMad** [comment]
既然用gfw模式，需要自定义大量的域名，可以善用规则管理中相应的规则订阅。规则列表栏目更多的是自定义简易可读性的维护列表。
或者试试直接编辑对应文件，不从luci录入。

**Comment by najloa** [comment]
> 既然用gfw模式，需要自定义大量的域名，可以善用规则管理中相应的规则订阅。规则列表栏目更多的是自定义简易可读性的维护列表。 或者试试直接编辑对应文件，不从luci录入。

多谢解答。重新编译版本后我更改了分流和dns设置，不在出现这个问题。
