### ISSUE TITLE
DNS过滤模式选择sing-box，就不能在TCP节点或sing-box分流的默认节点使用有CNAME记录的域名地址

### ISSUE THREAD

**Issue by najloa** [Openwrt-Passwall/openwrt-passwall#3139]
### 描述您遇到的bug

手动将机场域名地址改成CNAME指定的域名或ip可以正常使用。其它DNS过滤模式不受此问题影响。sing-box分流模式的分流节点（下图中的*Instagram * OpenAI）使用有CNAME记录的域名地址似乎也不受此问题影响。

节点信息：
![屏幕截图 2024-04-23 091008](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/4bf92b6f-d91b-4a54-b618-0e6958ceaa94)
![屏幕截图 2024-04-23 092130](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/ea8fe5ac-ff8e-4ec5-9d14-cadb7f477a19)

passwall设置：
![屏幕截图 2024-04-23 091259](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/47dea5e3-5b3b-4242-a0cf-c12735ea5f65)
![屏幕截图 2024-04-23 091232](https://github.com/xiaorouji/openwrt-passwall/assets/15027661/cf9764c0-caed-4a0b-9d71-ebfc270e280c)

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

无

**Comment by xcyll** [comment]
PW这边引用的是稳定版 Sing-Box当前版本是v1.8.11

**Comment by xcyll** [comment]
测试版 v1.9.0-rc.9解决了这个问题https://github.com/SagerNet/sing-box/commit/17aebc56c1b72696aa379a4806a6b73eb4fa3f85

**Comment by xcyll** [comment]
可能还有问题 最好等正式版吧

**Comment by xcyll** [comment]
暂时用其它过滤模式吧

**Comment by xcyll** [comment]
sing-box最新测试版是 v1.9.0-rc.9不知解决了这个问题没 我没测试

**Comment by nftbty** [comment]
这个跟Passwall无关了，看是不是Sing-Box的问题。passwall是直接把节点域名原样填入sing-box配置文件的，怎么解析这个域名是软件自身的事了。
可以进一步测试，不用passwall，用手机NekoBox或Windows的NekoRay测试同样节点试试，或者用生成的配置文件纯手动运行sing-box。
如果是sing-box问题，这个需要去sing-box那边提。

**Comment by gito10** [comment]
这个可以先确定下是passwall的问题还是sing-box的问题，可以不用passwall，用手机NekoBox或电脑NekoRay测试同样节点，看是否有问题。

**Comment by najloa** [comment]
> sing-box最新测试版是 v1.9.0-rc.9不知解决了这个问题没 我没测试

一样的问题

**Comment by najloa** [comment]
> 这个可以先确定下是passwall的问题还是sing-box的问题，可以不用passwall，用手机NekoBox或电脑NekoRay测试同样节点，看是否有问题。

NekoRay默认设置导入链接使用相同的节点，一切正常。

NekoRay日志：

正在启动配置 [Trojan] 新加坡 01
INFO[0000] inbound/mixed[mixed-in]: tcp server started at 127.0.0.1:2080
INFO[0000] sing-box started (0.00s)
INFO[0000] [2793994859 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49536
INFO[0000] [3887950337 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49535
INFO[0000] [3887950337 0ms] inbound/mixed[mixed-in]: inbound connection to api.github.com:443
INFO[0000] [1677645880 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49538
INFO[0000] [2793994859 0ms] inbound/mixed[mixed-in]: inbound connection to api.github.com:443
INFO[0000] [1982986986 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49537
INFO[0000] [1677645880 0ms] inbound/mixed[mixed-in]: inbound connection to api.github.com:443
INFO[0000] [1982986986 0ms] inbound/mixed[mixed-in]: inbound connection to api.github.com:443
DEBUG[0000] [3887950337 0ms] router: sniffed protocol: tls, domain: api.github.com
INFO[0000] [3887950337 1ms] outbound/trojan[proxy]: outbound connection to api.github.com:443
DEBUG[0000] [3887950337 1ms] dns: lookup domain sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro
DEBUG[0000] [3887950337 1ms] dns: match[0] domain=sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro => dns-direct
DEBUG[0000] [2793994859 1ms] router: sniffed protocol: tls, domain: api.github.com
INFO[0000] outbound/direct[direct]: outbound packet connection to 192.168.5.1:53
INFO[0000] [2793994859 1ms] outbound/trojan[proxy]: outbound connection to api.github.com:443
DEBUG[0000] [2793994859 1ms] dns: lookup domain sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro
DEBUG[0000] [2793994859 1ms] dns: match[0] domain=sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro => dns-direct
DEBUG[0000] [1677645880 1ms] router: sniffed protocol: tls, domain: api.github.com
INFO[0000] [1677645880 1ms] outbound/trojan[proxy]: outbound connection to api.github.com:443
DEBUG[0000] [1677645880 1ms] dns: lookup domain sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro
DEBUG[0000] [1677645880 1ms] dns: match[0] domain=sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro => dns-direct
DEBUG[0000] [1982986986 1ms] router: sniffed protocol: tls, domain: api.github.com
INFO[0000] [1982986986 1ms] outbound/trojan[proxy]: outbound connection to api.github.com:443
DEBUG[0000] [1982986986 1ms] dns: lookup domain sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro
DEBUG[0000] [1982986986 1ms] dns: match[0] domain=sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro => dns-direct
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro SOA sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN SOA a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro CNAME sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN CNAME gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro.
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.72
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.71
DEBUG[0000] [3887950337 2ms] dns: lookup succeed for sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro: 12◼️.◼️◼️.14◼️.72 12◼️.◼️◼️.14◼️.71
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro SOA sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN SOA a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro SOA sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN SOA a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro CNAME sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN CNAME gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro.
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.72
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.71
DEBUG[0000] [2793994859 3ms] dns: lookup succeed for sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro: 12◼️.◼️◼️.14◼️.72 12◼️.◼️◼️.14◼️.71
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro CNAME sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN CNAME gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro.
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.72
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.71
DEBUG[0000] [1677645880 3ms] dns: lookup succeed for sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro: 12◼️.◼️◼️.14◼️.72 12◼️.◼️◼️.14◼️.71
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro SOA sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN SOA a.gtld-servers.net. nstld.verisign-grs.com. 1800 1800 900 604800 86400
DEBUG[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro NOERROR 1092
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro CNAME sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro. 1092 IN CNAME gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro.
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.72
INFO[0000] dns: exchanged sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro A gtm-sg-dza3gmqkq03.◼️◼️sca◼️◼️y.pro. 1092 IN A 12◼️.◼️◼️.14◼️.71
DEBUG[0000] [1982986986 4ms] dns: lookup succeed for sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro: 12◼️.◼️◼️.14◼️.72 12◼️.◼️◼️.14◼️.71
INFO[0000] [1383525417 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49539
INFO[0000] [1383525417 0ms] inbound/mixed[mixed-in]: inbound connection to api.github.com:443
DEBUG[0000] [1383525417 0ms] router: sniffed protocol: tls, domain: api.github.com
INFO[0000] [1383525417 0ms] outbound/trojan[proxy]: outbound connection to api.github.com:443
DEBUG[0000] [1383525417 0ms] dns: lookup domain sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro
DEBUG[0000] [1383525417 1ms] dns: match[0] domain=sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro => dns-direct
DEBUG[0000] [1383525417 1ms] dns: lookup succeed for sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro: 12◼️.◼️◼️.14◼️.72 12◼️.◼️◼️.14◼️.71
ERROR[0000] [1982986986 234ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:49537: download: write tcp 127.0.0.1:2080->127.0.0.1:49537: wsasend: An established connection was aborted by the software in your host machine.
ERROR[0000] [2793994859 238ms] inbound/mixed[mixed-in]: process connection from 127.0.0.1:49536: download: write tcp 127.0.0.1:2080->127.0.0.1:49536: wsasend: An established connection was aborted by the software in your host machine.
INFO[0003] [2086900455 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49545
INFO[0003] [2086900455 0ms] inbound/mixed[mixed-in]: inbound connection to www.youtube.com:443
DEBUG[0003] [2086900455 0ms] router: sniffed protocol: tls, domain: www.youtube.com
INFO[0003] [2086900455 0ms] outbound/trojan[proxy]: outbound connection to www.youtube.com:443
DEBUG[0003] [2086900455 0ms] dns: lookup domain sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro
DEBUG[0003] [2086900455 0ms] dns: match[0] domain=sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro => dns-direct
DEBUG[0003] [2086900455 0ms] dns: lookup succeed for sgp-01-16a0e.◼️◼️◼️smig◼️◼️y.pro: 12◼️.◼️◼️.14◼️.72 12◼️.◼️◼️.14◼️.71
INFO[0003] [4048617804 0ms] inbound/mixed[mixed-in]: inbound connection from 127.0.0.1:49547
INFO[0003] [4048617804 0ms] inbound/mixed[mixed-in]: inbound connection to rr5---sn-npoe7nds.googlevideo.com:443
DEBUG[0003] [4048617804 0ms] router: sniffed protocol: tls, domain: rr5---sn-npoe7nds.googlevideo.com
INFO[0003] [4048617804 0ms] outbound/trojan[proxy]: outbound connection to rr5---sn-npoe7nds.googlevideo.com:443



相同节点passwall的日志：

+0800 2024-04-23 14:24:17 INFO router: updated default interface eth1, index 3
+0800 2024-04-23 14:24:17 INFO inbound/socks[socks-in]: tcp server started at 0.0.0.0:1070
+0800 2024-04-23 14:24:17 INFO inbound/redirect[redirect_tcp]: tcp server started at [::]:1041
+0800 2024-04-23 14:24:17 INFO inbound/tproxy[tproxy_udp]: udp server started at [::]:1041
+0800 2024-04-23 14:24:17 INFO inbound/direct[dns-in]: tcp server started at 127.0.0.1:15353
+0800 2024-04-23 14:24:17 INFO inbound/direct[dns-in]: udp server started at 127.0.0.1:15353
+0800 2024-04-23 14:24:17 INFO sing-box started (0.00s)
+0800 2024-04-23 14:24:29 INFO [626200436 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:46550
+0800 2024-04-23 14:24:29 DEBUG [626200436 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:29 DEBUG [626200436 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:29 DEBUG dns: exchange www.youtube.com. IN AAAA
+0800 2024-04-23 14:24:29 DEBUG dns: strategy rejected
+0800 2024-04-23 14:24:29 INFO [895760408 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:58856
+0800 2024-04-23 14:24:29 DEBUG [895760408 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:29 DEBUG [895760408 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:29 DEBUG dns: exchange www.youtube.com. IN A
+0800 2024-04-23 14:24:29 INFO outbound/trojan[rG3cRLCZ]: outbound connection to 1.1.1.1:53
+0800 2024-04-23 14:24:29 DEBUG dns: lookup domain sgp-01-16A0E.◼️◼️smig◼️◼️◼️y.pro
+0800 2024-04-23 14:24:29 INFO [2206170710 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:58669
+0800 2024-04-23 14:24:29 DEBUG [2206170710 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:29 DEBUG [2206170710 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:29 DEBUG dns: exchange www.youtube.com. IN HTTPS
+0800 2024-04-23 14:24:31 DEBUG dns: exchange www.youtube.com. IN HTTPS
+0800 2024-04-23 14:24:31 DEBUG dns: exchange www.youtube.com. IN A
+0800 2024-04-23 14:24:32 DEBUG dns: exchange www.youtube.com. IN HTTPS
+0800 2024-04-23 14:24:32 DEBUG dns: exchange www.youtube.com. IN A
+0800 2024-04-23 14:24:34 DEBUG dns: exchange www.youtube.com. IN HTTPS
+0800 2024-04-23 14:24:34 DEBUG dns: exchange www.youtube.com. IN A
+0800 2024-04-23 14:24:36 DEBUG dns: exchange www.youtube.com. IN A
+0800 2024-04-23 14:24:36 DEBUG dns: exchange www.youtube.com. IN HTTPS
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN A
+0800 2024-04-23 14:24:38 INFO [2374863473 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:35856
+0800 2024-04-23 14:24:38 DEBUG [2374863473 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:38 DEBUG [2374863473 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN AAAA
+0800 2024-04-23 14:24:38 DEBUG dns: strategy rejected
+0800 2024-04-23 14:24:38 INFO [1184989741 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:32770
+0800 2024-04-23 14:24:38 DEBUG [1184989741 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:38 DEBUG [1184989741 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN AAAA
+0800 2024-04-23 14:24:38 DEBUG dns: strategy rejected
+0800 2024-04-23 14:24:38 INFO [2046414356 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:46154
+0800 2024-04-23 14:24:38 DEBUG [2046414356 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:38 DEBUG [2046414356 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN AAAA
+0800 2024-04-23 14:24:38 DEBUG dns: strategy rejected
+0800 2024-04-23 14:24:38 INFO [3665588516 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:36696
+0800 2024-04-23 14:24:38 DEBUG [3665588516 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:38 DEBUG [3665588516 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN AAAA
+0800 2024-04-23 14:24:38 DEBUG dns: strategy rejected
+0800 2024-04-23 14:24:38 INFO [4219307972 0ms] inbound/direct[dns-in]: inbound packet connection from 127.0.0.1:54337
+0800 2024-04-23 14:24:38 DEBUG [4219307972 0ms] router: sniffed packet protocol: dns
+0800 2024-04-23 14:24:38 DEBUG [4219307972 0ms] router: match[0] inbound=dns-in protocol=dns => dns-out
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN AAAA
+0800 2024-04-23 14:24:38 DEBUG dns: strategy rejected
+0800 2024-04-23 14:24:38 DEBUG dns: exchange www.youtube.com. IN A

**Comment by xcyll** [comment]
sing-box这里其它平台的客户端试试https://github.com/SagerNet/sing-box/releases

**Comment by najloa** [comment]
> sing-box这里其它平台的客户端试试https://github.com/SagerNet/sing-box/releases

我将节点域名添加到直连列表和sing-box分流规则中的Direct，问题解决了。
