### ISSUE TITLE
[Bug]: 去掉dns2tcp后出现的问题

### ISSUE THREAD

**Issue by sss9091** [Openwrt-Passwall/openwrt-passwall#3245]
### 描述您遇到的bug

@xiaorouji 小肉鸡大佬你好，在dns2tcp去掉以后，发现了两个问题：

**一、18.06防火墙中插入dns劫持规则，或js luci版本中开启重定向dns，在不启用passwall的情况下可以正确劫持局域网内设备的dns请求，一旦开启passwall，劫持失效。在之前的版本中，开启passwall后是可以正常劫持的。**

可在局域网设备上用dig命令测试劫持效果（或者有其他类似工具指定dns也行）：
```
dig www.baidu.com @1.1.1.55
```
为什么要用这个IP呢？因为劫持成功后，所有去往53端口的请求都会被重定向到路由器本机53端口，只要劫持成功了必定会返回结果，否则会正常发送到目标地址，因为不是正确的dns服务器，所以拿不到结果。

以下规则来自lean 18.06：
```
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
```
以下规则来自lienol 21.02：
```
iptables -t nat -w -A PREROUTING -m comment --comment "Dnsmasq" -p udp --dport 53 -j REDIRECT --to-ports 53
ip6tables -t nat -w -A PREROUTING -m comment --comment "Dnsmasq" -p udp --dport 53 -j REDIRECT --to-ports 53
```
以下规则来自lienol 22.03：
```
iptables -t nat -w -A PREROUTING -m comment --comment "Dnsmasq" -p udp --dport 53 -j REDIRECT --to-ports 53
ip6tables -t nat -w -A PREROUTING -m comment --comment "Dnsmasq" -p udp --dport 53 -j REDIRECT --to-ports 53
```
以下规则来自immortalwrt 21.02:
```
iptables -t nat -A PREROUTING -m comment --comment "DNSMASQ" -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -m comment --comment "DNSMASQ" -p udp --dport 53 -j REDIRECT --to-ports 53
```

**二、宽带重新拨号后，上不了外网，根据已有反馈调查，发现是dns出问题了**
清空ipset后恢复正常。已有反馈#3188

@nftbty 希望大佬也能帮忙看看有没有什么好的解决办法，先谢谢两位大佬了。

### 复现此Bug的步骤

已在描述中说明。

### 您想要实现的目的

修复。

### 日志信息

2024-06-04 08:26:19: 清空并关闭相关程序和缓存完成。
2024-06-04 08:26:19: 分析 Socks 服务的节点配置...
2024-06-04 08:26:19: TCP节点：[分流总节点]，监听端口：1041
2024-06-04 08:26:19: DNS域名解析：
2024-06-04 08:26:19:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
2024-06-04 08:26:19:   - ChinaDNS-NG(127.0.0.1#15353)：直连DNS：打码，可信DNS：tcp://1.1.1.1#53
2024-06-04 08:26:19:   - 节点列表中的域名(vpslist)：打码
2024-06-04 08:26:19:   - 域名白名单(whitelist)：默认
2024-06-04 08:26:19:   - 代理域名表(blacklist)：默认
2024-06-04 08:26:19:   - 防火墙域名表(gfwlist)：默认
2024-06-04 08:26:19:   - 中国域名表(chnroute)：默认
2024-06-04 08:26:19:   - V2ray/Xray分流规则(ProxyGame)：127.0.0.1#15353
2024-06-04 08:26:19:   - V2ray/Xray分流规则(Proxy)：127.0.0.1#15353
2024-06-04 08:26:19:   - 默认：127.0.0.1#15353
2024-06-04 08:26:19:   - PassWall必须依赖于Dnsmasq，如果你自行配置了错误的DNS流程，将会导致域名(直连/代理域名)分流失效！！！
2024-06-04 08:26:19: 开始加载防火墙规则...
2024-06-04 08:26:20:   - [0]追加ISP IPv4 DNS到白名单：打码
2024-06-04 08:26:20:   - [0]追加ISP IPv4 DNS到白名单：打码
2024-06-04 08:26:20:   - [0]加入负载均衡的节点到ipset[passwall_vpslist]
2024-06-04 08:26:20:   - [0]加入所有节点到ipset[passwall_vpslist]
2024-06-04 08:26:20:   - [0]追加直连DNS到iptables：打码
2024-06-04 08:26:20:   - [0]追加直连DNS到iptables：打码
2024-06-04 08:26:20:   - 【路由器本机】，屏蔽代理 UDP 端口[443]
2024-06-04 08:26:20:   - [0]将上游 DNS 服务器 1.1.1.1:53 加入到路由器自身代理的 TCP 转发链
2024-06-04 08:26:20:   - 访问控制：
2024-06-04 08:26:20:      - 【默认】，屏蔽代理 UDP 端口[443]
2024-06-04 08:26:20:      - 【默认】，使用 TCP 节点[分流总节点](REDIRECT:1041)
2024-06-04 08:26:20:      - 【默认】，使用 UDP 节点[分流总节点](TPROXY:1041)
2024-06-04 08:26:20: 防火墙规则加载完成！
2024-06-04 08:26:23: 重启 dnsmasq 服务
2024-06-04 08:26:23: 配置定时任务：自动更新规则。
2024-06-04 08:26:23: 运行完成！

### 系统相关信息

4.77-5

**Comment by gito10** [comment]
关于第一个，DNS劫持的问题，我试了一下。我的op就是lean版，防火墙自定义规则里原本有，不过前段时间注释掉了。
刚刚取消注释，重启防火墙，重启passwall，测试是可以成功劫持的，也可以正常翻墙。（我的passwall是 4.77-6 版）

多几个人测试看看，有没有能够复现一样问题的。

**Comment by BGzEroll** [comment]
我用pve虚拟化了台imm21.02，关闭了dns重定向。主路由开启dns重定向，passwall为最新源码编译。在imm21.02上进行dig测试，**一切正常**。
![Screenshot_20240604_130445](https://github.com/xiaorouji/openwrt-passwall/assets/104726856/ab56a21b-ce0a-4dd2-a971-fd3d2b1e7cfb)

**Comment by sss9091** [comment]
我说说这个问题是怎么发现的吧，目前升级到4.77-6依然能复现。

手上一台iOS设备安装了QuantumultX，虽然是全局直连模式，但访问一些网站时发现会很慢，于是分析了一下DNS查询记录，发现某些域名走了8.8.8.8查询（走53端口的传统DNS模式，并非加密DNS），明明有国内CDN节点，Passwall里也配置了默认DNS直连，却依然通过8.8.8.8拿到了境外CDN节点IP，证明openwrt劫持失败了，导致访问网站很慢，之后我又用一台局域网内装了debian的小主机测了下，发现确实劫持失败了。

我找了一个可以复现的域名：
tam.cdn-go.cn

通过itdog.cn查询可以发现有国内CDN节点，dig命令查询结果如下：
```
# dig tam.cdn-go.cn @8.8.8.8

; <<>> DiG 9.16.44-Debian <<>> tam.cdn-go.cn @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8003
;; flags: qr rd ra; QUERY: 1, ANSWER: 12, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tam.cdn-go.cn.			IN	A

;; ANSWER SECTION:
tam.cdn-go.cn.		600	IN	CNAME	any.cdn-go.cn.tegsea.tc.qq.com.
any.cdn-go.cn.tegsea.tc.qq.com.	600 IN	CNAME	any.cdn-go.lmtlego.sched.apdcdn.com.
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	203.205.137.157
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	43.175.44.41
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	43.152.24.204
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	203.205.137.114
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	203.205.137.163
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	43.152.14.111
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	203.205.137.159
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	43.152.14.106
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	203.205.136.59
any.cdn-go.lmtlego.sched.apdcdn.com. 60	IN A	203.205.136.151

;; Query time: 96 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jun 04 20:49:40 CST 2024
;; MSG SIZE  rcvd: 292
```

然后使用一个非DNS服务器dig了一下，超时，证明没有劫持成功：
```
# dig tam.cdn-go.cn @8.8.8.88

; <<>> DiG 9.16.44-Debian <<>> tam.cdn-go.cn @8.8.8.88
;; global options: +cmd
;; connection timed out; no servers could be reached
```

当我关闭Passwall UDP节点后，就恢复正常了，可以正常劫持。
另外，我尝试将之前删除的一部分代码加回，问题也解决了：
https://github.com/xiaorouji/openwrt-passwall/commit/cf7003ff1d70bccd8c159d79d489e4ec34810d79#diff-9bc143043a6600231878b10092f1d0e2c6a523f4d613c44041d267134ad71d85L1112-L1113

**Comment by sss9091** [comment]
> 关于第一个，DNS劫持的问题，我试了一下。我的op就是lean版，防火墙自定义规则里原本有，不过前段时间注释掉了。 刚刚取消注释，重启防火墙，重启passwall，测试是可以成功劫持的，也可以正常翻墙。（我的passwall是 4.77-6 版）
> 
> 多几个人测试看看，有没有能够复现一样问题的。

可以分享一下固件吗，我测测

**Comment by jingyuan277** [comment]
imm21.02实测有问题，imm仓库自带的版本是4.68-1，编译出来的passwall可以重定向内网的dns请求，下载最新ipk升级或拉取最新源码编译都无法重定向内网dns请求。

**Comment by wtfr-dot** [comment]
我自编译的官方23.05，去掉nftables采用的iptables，我的防火墙自定义规则里没加入dns劫持规则，passwall的远程dns用udp方式丢给smartdns海外组解析，实测局域网内如果自定义了dns服务器，它会直接向dns服务器发起连接，我的chromecast就是这样，在passwall的udp节点log里可以看见它直接向8.8.8.8:53发起连接，但是如果局域网设备dns通过dhcp就没问题，因为dns是网关，这符合FAQ里关于dns的说明，我试了在防火墙的自定义加入dns劫持规则，虽然nat表里添加进了转发规则，但是dns劫持不生效，我看见passwall的iptables.sh里有dns劫持的代码，但是好像防火墙nat表里找不到这个规则链，只有一个PSW_REDIRECT的空连，从iptables看passwall好像没有在nat表里劫持dns，会不会是在mangle表里进行了处理，只是猜测，本人不懂代码

**Comment by wtfr-dot** [comment]
> 我自编译的官方23.05，去掉nftables采用的iptables，我的防火墙自定义规则里没加入dns劫持规则，passwall的远程dns用udp方式丢给smartdns海外组解析，实测局域网内如果自定义了dns服务器，它会直接向dns服务器发起连接，我的chromecast就是这样，在passwall的udp节点log里可以看见它直接向8.8.8.8:53发起连接，但是如果局域网设备dns通过dhcp就没问题，因为dns是网关，这符合FAQ里关于dns的说明，我试了在防火墙的自定义加入dns劫持规则，虽然nat表里添加进了转发规则，但是dns劫持不生效，我看见passwall的iptables.sh里有dns劫持的代码，但是好像防火墙nat表里找不到这个规则链，只有一个PSW_REDIRECT的空连，从iptables看passwall好像没有在nat表里劫持dns，会不会是在mangle表里进行了处理，只是猜测，本人不懂代码

刚才看了一下mangle表里对本地的dns有直连处理，需要代理的dns在之前进行了分流处理，不知道理解得对不对

**Comment by lwb1978** [comment]
试试编译最新的代码，新增了dns重定向功能（在dns设置页面）

**Comment by sss9091** [comment]
> 试试编译最新的代码，新增了dns重定向功能（在dns设置页面）

解决了，谢谢。
